### ISSUE TITLE
Paladin Spells: Xeno

### ISSUE THREAD

**Issue by bleehu** [trowl223/Compound_X#10]
What is a xeno?

**Comment by trowl223** [comment]
Demons, Astral Wraiths and Necrophages. High level type enemies. To be covered in a separate player document.

**Comment by bleehu** [comment]
which separate player doc?

**Comment by trowl223** [comment]
Probably the ARD's, maybe a general Lore document describing each of the major enemy groups and their relations and history with Sanity / ECSC. I'll get on that after our next bug fixes, I'm still currently designing spells for Mages and Sorcerers currently.

**Comment by trowl223** [comment]
Ewww, I said currently twice in the same sentence -_-

**Comment by bleehu** [comment]
Lore Docs still don't exist...

**Comment by Wildlovelies** [comment]
Bump

**Comment by bleehu** [comment]
@trowl223 Can we yank this spell? It's the only ability in the game that isn't agnostic to enemy type. I'd really like to kill this issue.

**Comment by trowl223** [comment]
Yank for now, I think we need to rework it so it flows with any environment and not just the Xenofaroxi Conflict universe.

**Comment by bleehu** [comment]
merged and completed!
