### ISSUE TITLE
Feature Request: Drunk Status Effect

### ISSUE THREAD

**Issue by bleehu** [trowl223/Compound_X#103]
We should have a condition for being intoxicated.

**Comment by trowl223** [comment]
Yes. There should be two effects with various stages of intoxication : Uppers and Downers. They should be part of the "Sickened/Ill" condition set so a GM can add extra side effects for certain substances.

**Comment by bleehu** [comment]
Does anyone else want it?

**Comment by bleehu** [comment]
I'm taking it!

**Comment by bleehu** [comment]
Awaiting @trowl223's ok for the alcohol warning.

**Comment by trowl223** [comment]
Yeah. I don't think the game needs to be family friendly. Its something we can always take out of the game too.

**Comment by bleehu** [comment]
We can't close the issue until the PR has been moved to dev (we probably shouldn't even close it until it's at least in RC, but we haven't been holding to that)
