### ISSUE TITLE
Review Gunslinger: Enhanced Gun Kata

### ISSUE THREAD

**Issue by 1sourcecontrol** [trowl223/Compound_X#106]
I think enhanced gun kata level 2 is far too powerful. The ability has no limit to uses per day, no stated action cost (so I assume it takes 1 action to use?), has the potential to kill every enemy (granting that the enemies are the same difficulty level) within sight & 35m kata range of the gunslinger, and a high-dex cyborg could feasibly reload several times in a single use of the kata. 
Gunslingers main limitation at close range would be his accuracy (which can be easily pushed below 0% miss chance) and ammo. I do not consider ammo a factor in this discussion because if a gunslinger is able to annihilate (for example) 8 targets with 4 mags of ammo (or less) in less than a turn, I'd just supply him with more ammo if I was playing with him. As well as the fact that, if the gunslinger can take a whole encounter by himself and run out of ammo, surely the rest of the (unused) party will be able to handle the rest of the encounters without him, it's like a free pass.

Suggested solutions: add a 'uses per encounter' limitation, nerf the ability for the gunslinger to reload in a given kata (maybe max 1 reload per kata usage), and make the kata consume his entire turn/ 3 actions/etc.

**Comment by trowl223** [comment]
Agreed. The Gun-Kata class ability was meant to reflect the gun-fights encountered in the John-Wick films, or in Equilibrium. We should re-work the feats or replace them, but I want the gunslinger class to still be a class which reflects John Wick / Jason Bourne / John Preston. At least in terms of ranged weapons, not necessarily unarmed combat as well. Although that may be an interesting angle to look at the class from . . .

**Comment by bleehu** [comment]
I think we can still capture that aesthetic without borking the game entirely.

**Comment by bleehu** [comment]
@trowl223 would you write a replacement for this and submit a pull request?

**Comment by bleehu** [comment]
I'd like to fix this bug much before we pick up again this fall.

**Comment by bleehu** [comment]
Bump

**Comment by trowl223** [comment]
Okay. I'll get to work on this this weekend when I have time.

**Comment by 1sourcecontrol** [comment]
Putting in the fixes with C2.0

**Comment by bleehu** [comment]
See changes to classes in this merge: https://github.com/bleehu/Compound_X/commit/d2061451041d0e0caf3b47ac4f0835bb75f0d12c
