### ISSUE TITLE
Paladin Spells: Divine Armour

### ISSUE THREAD

**Issue by bleehu** [trowl223/Compound_X#11]
Range?
+5 DR is negligible

**Comment by trowl223** [comment]
Will boost to +10/+15? its only 30 Nanites, so its average blocked incoming damage should be close to 30. Maybe it augments target armour with one token of +30 DR?

**Comment by bleehu** [comment]
I think players would find that more appealing

**Comment by trowl223** [comment]
Changed phrasing to +30 DR single use.
