### ISSUE TITLE
Feature/Rule request: Crouch and prone

### ISSUE THREAD

**Issue by bleehu** [trowl223/Compound_X#120]
1Sourcecontrol suggested adding rules for crouching and going prone into our ruleset. I think that's a great idea as well. Specifically, we need to know how many actions it takes and what effect it has on accuracies, both those shooting at the now-smaller target and the accuracy bonus for aiming from a more stable position.

**Comment by 1sourcecontrol** [comment]
I'm currently throwing it in the combat 2.0 update, but my plan is as follows:
**Crouching**: +10% defense, free action to crouch, 1 Action to stand up, -1 movement speed per action (minimum 1) while crouched
**Prone**: +20% defense, 1 Action to prone/un-prone, -5% gun miss chance while prone; +15% to be hit in melee; 1/2 movement speed while prone, rounding down.

I'm thinking it may be good just to make it so the player can't move while crouched, then the player won't have to do any division math to figure out their movespeed, and less complicated rules... 

Potentially also having crouch _not_ consume an action to un-crouch, but limit movement for the next action?

**Comment by bleehu** [comment]
Maybe a feat for a Gears Of War style roadie-run? (running while crouched) Looks great to me.

**Comment by bleehu** [comment]
Technically, we can't close this issue until the work in Combat2.0 is merged to dev, but 1Sourcecontrol has already done the work in PR #122

**Comment by bleehu** [comment]
Fixed when we merge combat 2.0 https://github.com/bleehu/Compound_X/commit/d2061451041d0e0caf3b47ac4f0835bb75f0d12c
