### ISSUE TITLE
Level 10 special ammo missing

### ISSUE THREAD

**Issue by bleehu** [trowl223/Compound_X#130]
We have no level 10 special ammo.

**Comment by trowl223** [comment]
As a suggestion, Vorpel rounds and phasing rounds were somewhere in one of my ideas documents. 

- Vorpel rounds add a bonus to crit and extra damage on crit, something in the realm of -10% to each crit tier, +10 damage. Magazine cost * 2.5 or 3.
- Phasing rounds add +10% to hit, even when target is in cover. Magazine cost *1.5

**Comment by bleehu** [comment]
What's a vorpel?

**Comment by bleehu** [comment]
I think I found it! https://www.urbandictionary.com/define.php?term=vorpal

It would be nice to add Gluon and shredder rounds to level 10 weapon rounds.

**Comment by 1sourcecontrol** [comment]
Wat! I've never heard of a Vorpel. It's more famous than I had thought. 

Can you add a comment for what the Gluon and shredder round stats are? We could add them to the attachments doc (after a C2.0 balance check)

**Comment by Turtlelord26** [comment]
Slightly more reputable source material for Vorpal, which is an adjective, not a noun.
http://www.dictionary.com/browse/vorpal?s=t

Obligatory aesthetic advisory.

**Comment by bleehu** [comment]
==================================================
//	Ammo 
==================================================

	Baffled Ammo
--------------------------------------------------
Reduces noise of bullet travel to zero and reduces noise of impact to a whisper.
Zero RP cost, but bullets are made of an organic material that decays after two
missions.

+ stealth rolls to hide silent weapons fire automatically succeed. 
+ a bullet impact can be heard if a character is within 5m of the impact, 
	actively curious and makes a search check over DC 50.
- reduces range by 10 m
- reduces damage by 5

--------------------------------------------------

	Gluon Rounds
--------------------------------------------------
These rounds contain an incompressible, unshatterable Gluon matrix. These 
rounds are manufactured by a luxury weapons corporation and are not available
to the public or military. They occupy 3 RP per clip.

+ Pierces armor and shields, no damage reduction for piercing cover
- after the tenth shot, 5% chance to jam weapon

--------------------------------------------------

	Shredder Ammo
--------------------------------------------------
Rounds splinter into hyperkinetic shrapnel upon impact. No RP cost,
but Rounds loose hyperkenetic charge after 2 missions and then
act like hollowpoints.

- multiplies armor resistance of target by 2.5
+ deals an additional 40 damage on hits
- reduces range by 10 m

--------------------------------------------------

	Short-circuit rounds
--------------------------------------------------
These rounds splinter into conductive metallic fragments soaked in piezoelectric
resin. The effect is that it resonates and crosses any signaling hardware that it
hits. However, these rounds trade this scrambling effect for penetration, and don't
penetrate armor as well. Occupies 1 RP

- If it hits armor or shields, it does no damage
+ deals an additional 60 damage on hits to security drones 
- reduces range by 10 m

**Comment by 1sourcecontrol** [comment]
What's an RP? Is this a quote from another game, modified to fit CX? Curious of the origins.

**Comment by bleehu** [comment]
I think it's a typo for EP
