### ISSUE TITLE
No class feats after level 10

### ISSUE THREAD

**Issue by bleehu** [trowl223/Compound_X#131]
Maybe this isn't an issue, but Players are going to hit level 15 in December and they will either run out of class feats to choose or will get a second class feat balanced for level 5. I recommend that we add a document to the level 10 folder that contains class feats that are balanced for level 15+ play.

As a comparison, 4E DnD would have whole separate classes for characters that reached level 10 called Heroic Classes. They also had classes that one could swap to at level 20 called epic classes. I'm not saying that we should use this model, but I do insist that we convey a continued sense of progression and things to explore after level 10.

**Comment by trowl223** [comment]
Class feats are currently built to go up to 20? there are 2 types of feats for each class, and two tiers of each. they aren't both level 5 / level 10 feats.

**Comment by bleehu** [comment]
alright. If you don't think it's an issue, we can close it out.

**Comment by 1sourcecontrol** [comment]
I think the current state is fine because there is at least progression, even if there isn't necessarily large jumps in power

**Comment by trowl223** [comment]
I do eventually come up with another pair of feats for each class, and maybe another tier of current feats. Maybe we can make that a stretch goal?

**Comment by bleehu** [comment]
I like stretch goals. :smile:
