### ISSUE TITLE
Using C encoding in rules

### ISSUE THREAD

**Issue by bleehu** [trowl223/Compound_X#136]
I've noticed that in addition to correcting spelling @1sourcecontrol is starting to clean up repeated apostrophes. 
But I also know that @trowl223 puts those in on purpose to conform with C language string encoding. 

Should we continue to string encode our text-based rules? I don't see why.

**Comment by trowl223** [comment]
No, @1sourcecontrol is doing God's work and should be commended for his effort in fixing my awful formatting hahaha

**Comment by bleehu** [comment]
Thus saith the TRowl! 

![](http://www.annielytics.com/wp-content/uploads/2016/11/and-there-was-much-rejoicing.jpg)
