### ISSUE TITLE
G&W XEV level 10 sniper has a 50m minimum effective range?

### ISSUE THREAD

**Issue by Michael-Hedges** [trowl223/Compound_X#14]
How does that make any sense?

**Comment by Michael-Hedges** [comment]
Same issue with the SRS Series 99

**Comment by trowl223** [comment]
Current convention is that long rifles have a penalty (10% of Max) minimum increment. Marksman are immune to this minimum, except that they must pass a reflex saving throw to fire within this range, probably a DC equal to the target's distance. If a non-marksman wants to share this immunity, they can pay for the tritium iron sights and use a free action to swap aiming devices. The reason for this is the assumption that high powered rifles come with scopes. When you're looking down a scope at high powered magnification (6x+), it's super difficult to focus on something very close to you. You'd need to adjust the focus, zoom, a combination of the two, or look outside the scope to focus on the close target.
https://en.m.wikipedia.org/wiki/Accuracy_International_Arctic_Warfare
Under Design Details, Accessories.
https://en.m.wikipedia.org/wiki/Barrett_M82
Under Technical Description, paragraph 3.
Even if all riflrs don't come /with/ scopes, most have preferred or partnered scopes developed for the rifle. Even the ACOG was made specifically for the .556 fired out of the M16/M4 platform:
https://en.m.wikipedia.org/wiki/Advanced_Combat_Optical_Gunsight
I'd be willing to look into decreasing this weapon penalty (although I do think it's reasonable), and I've been thinking of removing the damage debuff for firing within this range (bullet velocity is highest right when the bullet leaves the barrel, it should impart the most force and therefore deal the most damage in this range IMO, not be penalized. Good job, past me).
