### ISSUE TITLE
"Acquired:" in the feats list

### ISSUE THREAD

**Issue by 1sourcecontrol** [trowl223/Compound_X#143]
Hey trowl223/bleehu,

>Acquired: Additional Plating
Prerequisites: Marksman, Gunslinger
Enables the use of Medium Armour by the listed classes.

Why do a bunch of the feats have "Acquired: " in their name? Are those special feats of some sort?

**Comment by bleehu** [comment]
I think they are the ones that unlock armors for different classes, but they're Trowl223's. I can't say for sure.

**Comment by trowl223** [comment]
@bleehu is correct. Same ideas with the weapon unlock feats.
