### ISSUE TITLE
Combat 2.0 Rounding Terminology

### ISSUE THREAD

**Issue by Turtlelord26** [trowl223/Compound_X#170]
Currently in the pull request, combat 2.0 standardizes on a "drop the remainder" rounding terminology. While functionally identical to "round down" for positive numbers, it is very different for negative numbers. Dropping the remainder on a negative number is the same as rounding *up*.

Negative numbers can come up in poor rolls of untrained skills associated with a negative skill modifier, which is definitely corner case and +- 1 probably doesn't matter.

More seriously, negative Luck modifiers interacting with the new critical hit threshold equation are very important to keep precise. If I have 4 Luck, then either we "drop the remainder", in which case I crit on rolls of 10+ without other modifiers, or we "round down", in which case I crit on 11+ (yes, on a D10, I'm assuming we might have equipment that modifies crit range).

There are two issues I see with using "Drop the remainder" over "round down".
1. If we are dropping the remainder, then there is no difference for crit range calculations between having 3 Luck and 7 Luck. Obviously for most uses of Luck, like loot rolls, every point counts, but critical hit calculations are an important part of combat and this does create an incentive for people who dont want to allocate 8 points to Luck to go ahead and dump it all the way to 3. With "round down", the threshold values are 2, 5, 8, etc., which is a much tighter granularity.
2. I rather suspect that most people reading our rules would see "drop the remainder", but since they're probably only thinking about positive numbers, many would internalize it as round down as that's how many other games phrase it. People remembering this different ways could cause a DM to have to stop play and look up the rule to see the exact terminology.  Clarity in rules does extend beyond their self-contained system into the culture in which those rules will be used.
2.5. I'm not spectacularly confident the average group of not-professional-mathematicians would even all agree on what dropping the remainder of a negative number means. It's not exactly something that comes up often in everyday living. Any such disagreement would also possibly cause a play stop while the group worked it out.

I consider point 1 to be vastly the more important of the two, and it's very possible I'm doing the population a disservice with 2.5, but I figured I'd put everything on the table and see what people think.

**Comment by Turtlelord26** [comment]
@1sourcecontrol

**Comment by 1sourcecontrol** [comment]
My goal with "drop the remainder" was to make a more intuitive "round down" so you could avoid thinking about things like "which way do I round this negative number?" by removing anything to the right of the decimal place. 
So that: 10.222323 = 10 and -10.375 = -10

I did take your mention of critical hits with luck to heart and put rounding down in the rules.

Frankly, when I was thinking about all this, I wasn't sure whether 'rounding down' rounds towards zero or away for negative numbers.  I think we should add a glossary definition of rounding down and/or dropping the remainder so that the rules will be crystal clear to the player.

**Comment by bleehu** [comment]
@Turtlelord26, What's the action needed on this?

**Comment by Turtlelord26** [comment]
Well, the relevant case was handled, so it becomes a question of whether we mind a lack of standardization in our terminology (i.e. some 'round down' and some 'drop remainder' instead of all 'round down'). If we don't mind, then no further action is necessary. If we do, the action is lots of control-f and control-v in several documents.

**Comment by bleehu** [comment]
I don't mind. Do you?

**Comment by Turtlelord26** [comment]
Vaguely but I suppose not seriously.
