### ISSUE TITLE
Math error in Character_Sheet_Editable

### ISSUE THREAD

**Issue by rosebrallier** [trowl223/Compound_X#181]
Calculation for Fort mod is x5 instead of x4. https://github.com/bleehu/Compound_X/blob/play/CX_Character_Sheet_Editable.pdf

**Comment by Reveraine** [comment]
Thank you! I've fixed it in the base file. 
I'll upload it when I get home.

**Comment by bleehu** [comment]
@Reveraine any luck?

**Comment by bleehu** [comment]
Replaced!
