### ISSUE TITLE
Feats that need descriptions

### ISSUE THREAD

**Issue by Wildlovelies** [trowl223/Compound_X#182]
Acquired: The Stealth Option
Prerequisites: Soldier, Engineer, Doctor, Priest, Pilot, Adept, Gunslinger, 
Warlock, Monk, Berserker

Acquired: With Friends Like These . . .
Prerequisites: Pilot, Engineer or Piloting 40

Acquired: . . . Who Needs Nano-Technologies?
Prerequisites: Pilot or "Acquired: With Friends Like These . . ." and Piloting 60

**Comment by bleehu** [comment]
I think Acquired: The Stealth Option
is unlocking cloaking armor for the listed classes.

Acquired: With Friends Like These
is unlocking exo skeletons

Acquired: Who Needs Nano-tech
is unlocking  power armor

My advice is to yank all three. We'll add exo suits and power armor with the power armor superbranch project. I don't think stealth armor should be available to a berserker, doctor, etc at all.

**Comment by bleehu** [comment]
What do you think, @1sourcecontrol ?

**Comment by 1sourcecontrol** [comment]
I guess I'm not sure... How do we want to let a class have access to exoskeletons? Or the pilot access to powered armor? (hearkening back a while... I believe our powered suit design goals were to offer every class an exoskeleton option but to only offer powered armor to the pilot, right?)

I think the pilot's powered armor should be a class feature that just automatically 'happens' at level 5 or something like that.
I think it would be reasonable to make a general exoskeleton (non-powered-armor) training feat for all the classes, as well.

As far as stealth goes.. similar question.. do we want a mix of classes that start with access to cloaking and some can acquire it by a feat? Or just class access? I think it fits well for a pilot, soldier, gunslinger, or even a medic to have the ability to access -- it fits the 'be who you want to be' aesthetic (with some cost).
Although, I know it will devalue assassin/etc. a bit, similar to giving heavy weapons access to all classes beyond specialist. But if we skill/feat/price gate the usage of cloaking devices, as well as giving the assassin/etc. unique and awesome cloaking bonuses/differences in kind, then I think it would be really cool!

As far as Berserker is concerned, I think it may be part of the class design not to be stealthy. But we could leave that up to the player, right? although it's a bit of a divergence from the name 'Berserker', I certainly would like to play a smart-tactical cloaking Berserker. --It would be an 'ambusher' (any votes for that as a subclass of Berserker, eh-eh?)

What do you guys think?

**Comment by Turtlelord26** [comment]
What's the difference between a smart-tactical cloaking berserker and a strength-based hand-to-hand assassin? Ahhh glorious combat 2.0 stat system.

As far as the feats are concerned, I think we could just write into the class passives 'gain proficiency with powered armor (or whatever) *at level X*".

I vaguely lean toward letting specialists/pilots/stealthies have exclusive control over their fun toys, especially in the case of assassins where they straight up can't ever have proficiency with a primary weapon. It's my hope that we can find ways to make every class fun without diluting their identities by spreading every capability around. If we want to enable the 'I am a medic but also have stealth combat' amalgam type of character, we could consider implementing a cross-classing system to more accurately represent the amount of time it takes to learn that much stuff.

**Comment by 1sourcecontrol** [comment]
To be clear: I'm talking about powered armor and exoskeletons as two different things

**Comment by bleehu** [comment]
I agree emphatically with Turtle's statement "It's my hope that we can find ways to make every class fun without diluting their identities by spreading every capability around." I would even take it further to say that I would oppose _MOST_ implementations of a cross-class system. 

But that's a bit of a bunny trail, isn't it? On the specific topic, I'd like to yank these three feats. I suggest we handle adding exoskeletons when we merge the exoskeletal superbranch and we actually _have_ exoskeletons to unlock.

**Comment by 1sourcecontrol** [comment]
@bleehu  Yes, yes. I agree that there's a lot of value in giving each class unique toys. 
However, there is a difference between specialist getting access to heavy weapons versus assassins and hunters getting access to cloaking -- everybody gets access to weapons.
Stated another way: heavy weapons are to weapons as cloaking is to _____? There is no other item that is similar to what cloaking is. That's why I'm hoping for some dilution here. Even just giving people the ability to acquire something like the passive camo module and nothing more. https://github.com/bleehu/Compound_X/blob/8752a1d6a725b24e8994bfebc3e8e08af9a65106/CharacterCreation/05_ArmourList.txt#L599
That module is a far cry from a normal cloaking module, but it gives some better broad-daylight capability than "you can't role stealth because you're standing in the open".

Fair enough, let's yank them.

**Comment by 1sourcecontrol** [comment]
Whoever yanks them, if you yank them from dev, please add a line under https://github.com/bleehu/Compound_X/blob/8752a1d6a725b24e8994bfebc3e8e08af9a65106/CharacterCreation/05_ArmourList.txt#L572
to tell the player that only *specific* classes can use stealth equipment, not the normal Joe.

**Comment by Turtlelord26** [comment]
Passive Camouflage armor / armor upgrades (probably limited in application by armor type) sound like an excellent feature and probably deserve their own feature request issue.

I was only ever thinking in terms of the restriction of active high-tech invisible-type stealth equipment.

**Comment by 1sourcecontrol** [comment]
Sounds good!
