### ISSUE TITLE
Adrenaline rush needs balanced

### ISSUE THREAD

**Issue by Wildlovelies** [trowl223/Compound_X#184]
Adrenaline Rush [20* X]: 
Run double your movement distance for X # of turns.

I limit this feat when i dm to 1m+ per action, but i let it stack with sprinting, making +2m per action (up to 8m per turn increase) Because i honestly think it is way too over powered. But i would like to hear other people's thoughts

**Comment by bleehu** [comment]
1SourceControl patched that in Combat 2.0:
https://github.com/bleehu/Compound_X/blob/combat2.0superbranch_AlexL/play/PlayerRules/CharacterCreation/03_Feats.txt#L474
We really should have not rolled that one atomic change into that superbranch. It should have been a separate smaller branch which then would not have been blocked with the other review of 2.0.
