### ISSUE TITLE
Semi redundant aiming feats

### ISSUE THREAD

**Issue by Wildlovelies** [trowl223/Compound_X#185]
Aimed Shot [10 Nanites]: 
Add an action to your normal Shooting time. During this time you concentrate 
on your target in order to deal crit damage on your next shot. This is akin to 
seeing a chink in armour and aiming for it, or shooting a target''s arm so 
they cannot use their weapon, etc.

Steady Shot: 
Take 1 Action to breath slowly and line up your shot. -5% miss chance and 
+10m range each per level taken. Maximum 4 levels.

Making sure this is intended, and not something overlooked

**Comment by bleehu** [comment]
@1sourcecontrol modified them in 2.0:
https://github.com/bleehu/Compound_X/blob/combat2.0superbranch_AlexL/play/PlayerRules/CharacterCreation/03_Feats.txt#L543
and
https://github.com/bleehu/Compound_X/blob/combat2.0superbranch_AlexL/play/PlayerRules/CharacterCreation/03_Feats.txt#L480

I think he's done a pretty good job of differentiating them, and I think they stack in a way that's cool, helpful, but not broken. Didn't do a full regression though, so @Wildlovelies if you see something I missed, please say something.

**Comment by bleehu** [comment]
This is super stale. Closing out. @Wildlovelies, you can reopen it if you still have concerns.
