### ISSUE TITLE
Redundant nanite feats

### ISSUE THREAD

**Issue by Wildlovelies** [trowl223/Compound_X#186]
Focus Energy: 
Spend 2 Actions to increase the effects of a spell or Nanite based 
action by 20%, (20% better roll, 20 damage, up to you.)

Nanite Concentration:
Prerequisites: Level 5
Allows the user to better concentrate on their expenditure of nanites, 
allowing them to achieve one of the following:
    +1 turn of cloaking
    +20% to an combat-action at a cost of 20 nanites for 1 turn (ask GM before applying to an action. )
    +20% to a non-combat-action at a cost of 20 nanites for 1 turn (ask GM before aplying to an action.)
Others, run any ideas by GM.

**Comment by 1sourcecontrol** [comment]
In C2.0 it's

>Focus Energy: 
Prerequisites:
Spend 1 Action to increase the effects of a spell or Nanite based 
action by 30%, (30% better roll, +30% damage [drop the remainder], up to you.)

>Nanite Concentration:
Prerequisites: Level 5, 20 skill in Knowledge[Nanites]
Allows the user to better concentrate on their expenditure of nanites, allowing them
to achieve one of the following (you must choose one option when you acquire the feat):
    +2 turns of cloaking
    Once per turn, +20% (or +2) to a Nanite-related-combat-action at a cost of 20 nanites (ask GM before applying to an action.)
    Once per turn, +20% to a non-combat-action at a cost of 20 nanites (ask GM before applying to an action.)
    Other, run any ideas by GM.

What do you think?

**Comment by bleehu** [comment]
I think the two offer a good difference in kind. Closing stale issue.
