### ISSUE TITLE
External Augmentations cost EP instead of credits

### ISSUE THREAD

**Issue by dragnagarge** [trowl223/Compound_X#2]

**Comment by trowl223** [comment]
Wrong version of External Augments was pushed to Play.

**Comment by bleehu** [comment]
Who has two thumbs and owns the fault for that issue? This guy. 
Issue fixed. 
https://github.com/trowl223/Compound_X/blob/master/play/PlayerRules/CharacterCreation/8.%20External%20Augmentation.txt
