### ISSUE TITLE
Define "Opportunity Attack" in the glossary

### ISSUE THREAD

**Issue by 1sourcecontrol** [trowl223/Compound_X#203]
I think we should define "Opportunity Attack" or "Penalty Attack". What do ya'll think?
If we define 'Opportunity Attack' we should remove 'Penalty Attack' from the melee rules (in the basic rules doc).

**Comment by bleehu** [comment]
I think we should definitely define Opportunity Attacks, and I think we just call them Opportunity attacks to draw from the similar mechanic in DnD. 
My outstanding question is "should we put rules in the glossary?"
I like the idea of having pointers to rules docs, rather than put rules themselves in the glossary of terms.

**Comment by rosebrallier** [comment]
I agree with Michael that rules should be well defined in the rules docs, and the glossary can refer players to the correct part of the rules docs. Btw, how do we plan on defining Opportunity Attacks?

**Comment by 1sourcecontrol** [comment]
I agree with one exception, we should make the glossary a quick reference for any game terms, which would include "Opportunity Attack". So if the basic rules say the following, "An Opportunity Attack is a free attack that typically occurs as a reaction to an opponent moving away from melee combat or moving past you when you have a melee weapon drawn. Other abilities can grant you opportunity attacks to shoot opponents at range, attack in melee, etc. Opportunity Attacks must be taken the moment they are triggered."

Then I would expect the glossary to say something like, "Opportunity Attack: a (typically) free-action reactionary attack"

**Comment by bleehu** [comment]
Can do. Fair warning though, at some point the definition of a term will change and it will get changed in the rules, but someone will forget to update the Glossary and we'll have a player catch a contradiction. Not the end of the world, but a very likely future pitfall.

**Comment by 1sourcecontrol** [comment]
I think it's totally worth the risk of missing a change or two. Having a quick reference will make our game tons easier to play, rather than requiring players to either memorize the whole rules doc or skim the whole rules doc for one small fact.

Maybe we should include this note in the design guide? "When changing a term definition, make sure to update the glossary"

**Comment by 1sourcecontrol** [comment]
Merged in #216 

Closing and continuing discussion in another issue.
