### ISSUE TITLE
Race Quality: 10RP?

### ISSUE THREAD

**Issue by bleehu** [trowl223/Compound_X#206]
Does anyone know what the heck this means?
https://github.com/bleehu/Compound_X/blob/dev/CharacterCreation/01_Races.txt#L94

**Comment by 1sourcecontrol** [comment]
I thought it was like "roleplay points" ... Wasn't there some RP items in the misc items that you could spend RP on? Maybe I have some misconceptions. 
I know there was something about "start with two roleplay items in your characters inventory" but maybe that's separate.

**Comment by 1sourcecontrol** [comment]
I asked Taylor, "That's an artifact of the pathfinder race creation tool I used to create each race. It was a way of making sure each race was more or less equal, I used that tool and tried to make each race only use 10 racial points to buy abilities and stat mods."

If someone could be so kind as to delete my previous comment.. I was way wrong. Lol (I can't see how to delete it from my phone)

**Comment by bleehu** [comment]
So we should yank the 10RP thing?

**Comment by 1sourcecontrol** [comment]
Yeah, it's a dev note

**Comment by bleehu** [comment]
See PR

**Comment by bleehu** [comment]
Fixed in PR #211
