### ISSUE TITLE
Lanugages are a mess

### ISSUE THREAD

**Issue by bleehu** [trowl223/Compound_X#209]
So... Languages are a mess. They apparently are given out by your Race, but some are given "ECSC standard" some "Basic" and some "Emperial Common" [SIC]. Opalites don't even have it mentioned. (That last one is my fault.)

To resolve this ticket specifically, can we yank language as a hard-"coded" rule system as a whole and maybe re-implement it, maybe not? 

If/When we do re-implement language, maybe we can add a separate small rules document listing the available languages. Maybe we can add ways of learning languages as you level up? Maybe we can even have a semi-realistic sociological model wherein each species has more than one language and maybe even have language cross the Racial boundary, but fall more along political or geographic boundaries?

**Comment by Reveraine** [comment]
While language and race makes sense, I think language and background make more sense to go together?  We can assume that each alien race has at least one language, but you are right, they need to be listed if they are a big part of immersion in the game.

**Comment by 1sourcecontrol** [comment]
I think we should either yank or homogenize our current implementation. Idk about the rest of everyone but I miss the DND aesthetic where I could speak Elvin and common, and it really came in handy sometimes if I was the only elvin speaking person. Or I could talk to another teammember without anyone understanding us.
But I think we could just homogenize the current implementation and give everybody common or Imperial common until a later date when we decide what to do with it. 

If each species has more than one language.. I would get headaches. Unless it's well segregated by each individual race in the race doc (like if elves were a subclass of humans, for instance) and everyone speaks common. And we'd run into problems where an entire party couldn't communicate if each character took a different language and didn't standardly have common.

**Comment by Reveraine** [comment]
There was some talk of having a Universal Translator of some sort. This way, for the most part it would be an aesthetic choice. Unless a DM specifically wanted send their players through a 'You UT broke, Does anyone speak Fish?' scenario.

I agree with not making it too complex. I think a universal translator analog helps keep the realism alive without adding complication for new players. 

As far as for now, yanking them seems fine as long as we continue dialogue about it.

**Comment by Reveraine** [comment]
Also!
Programming languages are incredibly relevant. For Example: Do nanites all speak C++, or can you program some with Python? What is droid X written in and do you have the equipment to hack that?
This should be an incredibly simple language system, if we decide to use it, but it's a thought I've had.

**Comment by bleehu** [comment]
Let's continue the design discussion here, and I'll make another issue ticket to track the work of yanking the current language system.
I had no idea you liked the DnD language system, Alex! I think I was under-valuing it before if that's the case. 
I really like the idea of a Universal Translator. There are several ways we could take that. What if we sold it at a similar price to radios?

**Comment by 1sourcecontrol** [comment]
There are definitely pros and cons to the DnD system, but the DnD system felt real to me. "I can't talk to that Elf because he only speaks elvish and I only speak common". Whereas, in CX, it appears we have a homogenized culture where almost everyone speaks common. 

I forgot about the Universal Translator haha, what sounds good to you?
I like that idea about programming languages. Maybe we could have 2 or 3, so that a hacker has more of a reason to get knowledge of skill (X).

**Comment by bleehu** [comment]
Let's spin the programming languages talk off into another forum (maybe in the design repo?) and keep this one about spoken/written languages specifically. @Reveraine has some really good work on Tundari language. 

Does anyone have any problem with universal translators being a cell-phone sized device available for purchase at level 1?

**Comment by Turtlelord26** [comment]
Programming languages already has an issue in the design guide.

No problem, because language barrier plot difficulties should only be a part of campaigns where the DM specifically wants it and knows what they're getting their group into.

**Comment by bleehu** [comment]
Can I close this?

**Comment by Turtlelord26** [comment]
According to your initial post, yes.
It would be better to continue the discussion this rabbit holed into after we know the rest of the racial mechanics anyway.
