### ISSUE TITLE
Add Quotes In Glossary

### ISSUE THREAD

**Issue by bleehu** [trowl223/Compound_X#214]
As 1Sourcecontrol mentioned, we should wrap references to Rules in other sections in quotes. Especially in the Glossary.

**Comment by 1sourcecontrol** [comment]
Although, if we choose to introduce formal indexing and a table of contents, then we can replace references with numbers.

Indexing such as the following:

======================
1 Combat

======================




===== 1.1 Ranged Combat =====

1.1.3 Weapon Jams:

**Comment by bleehu** [comment]
I love the idea of indexing. I love it hard. The only downside is that if we add a section in the middle, we have to update each number that follows it.

**Comment by 1sourcecontrol** [comment]
We could increase each index by two? That would allow at least 1 change to be added. But really, we could do that when we think we're done with most major changes.

**Comment by bleehu** [comment]
I think missing numbers would lead to more confusion. But I like the clever algorithm.

**Comment by 1sourcecontrol** [comment]
I hadn't thought of that. Fair enough, haha!

**Comment by bleehu** [comment]
work done, PR in review. will close when merged. unassigning myself so I can tell which of my 33 assigned issues still need work...
