### ISSUE TITLE
search skill

### ISSUE THREAD

**Issue by Wildlovelies** [trowl223/Compound_X#22]

**Comment by Michael-Hedges** [comment]
What's the issue with the search skill? Can you provide more detail?

**Comment by Wildlovelies** [comment]
Taylor griped that

**Comment by trowl223** [comment]
We don't have a "search" skill. The skills system as a whole needs a look over. I think we should have a closed pool of skills and those need to be decided on.

**Comment by trowl223** [comment]
Added.
