### ISSUE TITLE
Redesign Classes

### ISSUE THREAD

**Issue by 1sourcecontrol** [trowl223/Compound_X#223]
Until/In lieu of an actual meeting, I've started working on a proposal for class redesign and I want to stir up some discussion. (And to cover my bases: I've put a foot forward on the other (workable) dev priorities above this.) Sorry about the wall of text:

We've been discussing having base classes and a bunch of sub-classes based off of the original classes. 
In my opinion, big issues immediately arise if merge classes together:
1. Player variance gets reduced. Players will share more similarities during early levels if they have the same base class -- this will occur more often than we currently experience due to sub-classing.
2. Too much commonality may cause worse gameplay at early levels. What happens if two dissimilar-enough classes get the same base class? Example: assassin and soldier under the same base class. Normally assassins only get access to pistols and melee. But that would be quite lackluster for someone heading towards soldier. 
Q: So what if we give carbine proficiency to assassin and soldier?
A1: It changes the aesthetic of a given class. Access to certain weapon types is one of the largest distinguishing characteristics between different classes, and new playstyles would be added (which can be good or bad). 
A2: I don't know if we've ever addressed how we currently depart some from our CX armature, "be who you want to be." If we really went for that armature 100%, I think we'd have 1 generic class that you can mold into almost anything you _reasonably_ want. "Cloaking shotgun assassin," "powered armor soldier," "gunslinger medic," or even "marksman particle tech." But I think our departure from this level of malleability is fine because there already is a lot of variance to do minor flavors of most of these. And having strict weapons per classes would still allow some minor flavoring of the aforementioned. 
Q: So what if we give carbine proficiency to assassin and soldier, then take it away from assassin when we subclass?
A: There are several negative reasons but I'll give one: If assassin doesn't get a carbine (i.e. the best weapon available to his base class) at early levels because he knows he is going to be an assassin, he's choosing to be less effective early on. Normally we give players the option to, "be good now and awesome later" or "be great now and great later" because they aren't forced to waste money - classes never lose the ability to use certain weapons. But this scenario gives assassins the new option to "be bad now or awesome later."
Q: What about giving different weapon proficiencies at the start of the game, depending on what you want to subclass into?
A: The more you make it variable, the more it's like how we have classes now. (Some base class variability can be good! Depending on our goals.)

To address these potential problems, I _tentatively_ propose:
- Two sub-classes per base class be the norm. That will more than halve the number of classes (due to the probable removal of Monk) while still giving us a lot of variety so we don't have to make too many classes look the same at early levels. 
- I propose considering an earlier (~lvl 3) gain of a bonus ability/skill choice/sub class. I remember one of the concerns we've had at a dev meeting was that leveling up sometimes doesn't feel special. If we make the classes gain more stuff (every 3/4 levels instead of every 5) that can help fill out the leveling system more. I.e., if we do it carefully, we can have more than just "gain skill points" on more of the levels. Also, having an earlier bonus ability/subclass/whatever will help players be less similar at early levels.
- Do ya'll want soldier to still be a class by itself? I think it would be cool to still have the Soldier's style of gameplay. Although sub-classes could definitely be renamed if ya'll think the name 'soldier' should be the base class itself? 
- Do ya'll want a halfway point between soldier and the tech classes? I hope we can put Adept in that spot, rather than removing Adept.

_TLDR_: Stephen hates the phrase 'yolo'; also, this post took me a few hours to write.

**Comment by bleehu** [comment]
**Proposal 1)** I like setting the average character branch to be a binary choice. I think that gives us a good balance between nuking player choice and reducing the number of classes we need late-game content for. 
**Proposal 2)** I like giving the players more bonuses for leveling up. We need to be careful not to overshoot it though.
**Proposal 3)** Please keep soldier. I only care a little bit what we call him, but the vanilla Soldier is one of my favorite classes.
**Proposal 4)** I'm super down for an Adept class with a more fleshed-out idea of what he's actually supposed to _BE_. Otherwise I was thinking about dropping him.

**Comment by Turtlelord26** [comment]
re 4) I was intending to include a subclass of GravTech with a short-range tanking focus. Is that close enough to satisfy your desire for Adept?
Alternatively, I suppose I could see it as a subclass that gets minor access to tech abilities and shares a base class with vanilla soldier. But what do we give vanilla soldier besides exclusive access to battle rifles?

**Comment by 1sourcecontrol** [comment]
@Turtlelord26 
re __4)__ I forgot to mention Paladin in my first post. I would think Paladin (under a different name) would fulfill the short-range tanking roll. Otherwise we need somewhere to put Paladin or remove it. 
I was hoping adept would be a damage-output hybrid between a soldier and tech class. 
I think your alternative is a good idea for adept. I think vanilla soldier would have a lot of focus on movement abilities and initiative. While the Adept would give most of the movement/initiative abilities up for some tech damaging abilities. 

Disclaimer: all the stuff I've brought up about how, "I think adept/paliwin/soldier should be like _x_" is just opinion. I leave it up to @Reveraine to ultimately decide if that's the best direction for the classes. :)

**Comment by 1sourcecontrol** [comment]
It's been 3 months since I've last heard of any *significant* progress on this topic. Do we need to have an internet meeting to make more progress? @bleehu

**Comment by bleehu** [comment]
I take it this means you don't want to wait until you're back in state to have the meeting in person?

**Comment by Turtlelord26** [comment]
I really want there to be a whiteboard for this discussion.

**Comment by 1sourcecontrol** [comment]
@bleehu absolutely.

#315 
Quoting @Turtlelord26 :
>Maybe lovelies' proposals are subclasses of Engineer and Medic that cross a little into each others' domain, letting parties that need them have them, and letting characters for whom the cross would not make RP sense avoid it.

In specific regard to repairing robots and healing organics.

**Comment by bleehu** [comment]
@Turtlelord26, Do you think we can close this and bring it up at the next design meeting anew?

**Comment by Turtlelord26** [comment]
Yes.
