### ISSUE TITLE
Nanites in Medic Procedures

### ISSUE THREAD

**Issue by 1sourcecontrol** [trowl223/Compound_X#228]
If you open up the "procedures" doc and search for "nanites" you will find 5 instances. 
I believe these need to be removed?

**Comment by bleehu** [comment]
I have a half-finished branch with this work on my local, haven't found the time to wrap that up yet.

**Comment by bleehu** [comment]
Handled in PR #202 Will close on merge.

**Comment by bleehu** [comment]
weird that github isn't catching the PR #202 integration. Closing due to merge.
