### ISSUE TITLE
Races should list Anatomy

### ISSUE THREAD

**Issue by bleehu** [trowl223/Compound_X#233]
As we accrue more and more fun alien races, we should add an anatomy section to each race in the races document that describes the physical appearance of each of the species. Probably a job for aesthetic/lore team? Not a high priority, but raising an issue here to track the work.

**Comment by 1sourcecontrol** [comment]
Woop woop!

**Comment by bleehu** [comment]
We may need a dev to pair up with the Lore team for this one. I hear they have a rough draft in docs for it.

**Comment by bleehu** [comment]
@Reveraine, I noticed that the new Tundari and Human species files don't have anatomy sections. Are we still doing this? Are you saving anatomy for last?

**Comment by bleehu** [comment]
Please see PR #746 and PR #747. Because if you don't do something for a whole year, eventually I'll pick it up myself.

**Comment by bleehu** [comment]
Closing; these will ship with the new species re-work
