### ISSUE TITLE
Quality Check Medic 2.0

### ISSUE THREAD

**Issue by bleehu** [trowl223/Compound_X#234]
There are some concerns about the balance of Medic 2.0. Leaving myself a note to do the work, and a request for @Turtlelord26 who is currently playing the class and @Wildlovelies our head tester requesting peer review on balance of the powers and player choices involved.

**Comment by Turtlelord26** [comment]
I think you have me confused with someone else. I have a pilot and an engineer.

**Comment by bleehu** [comment]
Oh. I guess since you were raising issues I thought you were playing one. My bad. Will confer with another player.

**Comment by Turtlelord26** [comment]
All of the issues were base Engineer, Medic became involved due to the similarity of their ability trees.
