### ISSUE TITLE
Remove Copywrite notice from the bottom of each file

### ISSUE THREAD

**Issue by bleehu** [trowl223/Compound_X#238]
This is making the parser choke, and I don't think we need it on every file? Also, since this isn't technically 'software' I'm actually not sure this notice ever held any water whatsoever.

**Comment by 1sourcecontrol** [comment]
Frankly, I don't know the details of how the 'free copyright' even works. I'll take it

**Comment by bleehu** [comment]
Thanks for adjusting the labels correctly! :D

**Comment by 1sourcecontrol** [comment]
I try! haha
