### ISSUE TITLE
C2.0 weapon & armor systems

### ISSUE THREAD

**Issue by 1sourcecontrol** [trowl223/Compound_X#243]
I may be jumping the gun a little, but I still have large concerns with how I implemented weapons and armor in C2.0. They are quite realistic and thus, quite complex.

Our current implementation:
- Semi auto - full damage with 1 shot fired
- Burst - full damage with 3 shots fired with a moderate miss chance penalty. Consumes 3 ammo.
- Auto - full damage with 5/6+ shots fired with a large miss chance penalty. Consumes 5/6+ ammo.
- Difficult to be 100% immune to damage unless you have 100% coverage armor.
- Players are protected from getting 1-shot, when armor is pierced, by having temporary hitpoints ('armor points' that refresh every turn). Hits do 1/2 damage if armor is missed.
- If Armor Piercing level is higher than a given weapon's Armor Piercing level, every hit to armor is ignored. (This helps deal with the extreme damages attainable with burst/auto weapons.)
- Several edge cases for hitting armor or missing armor -> increased complexity

My thoughts on a new implementation (this includes less realism for weapon damages; I consider it more abstract):
- Semi auto - full damage with 1 shot fired
- Burst - 1/2 damage; rolling x2 (full damage if both hit) and a slight accuracy bonus. Consumes 3 ammo.
- Auto - 1/2 damage; rolling x4 (double damage if all hit) and a slight miss chance penalty. Consumes ~6 ammo.
- 2 different damages listed per weapon, one for hitting armor and one "full" damage for not hitting armor.
- Armor is always hit (100% coverage, if you will), no armor rolls.
- Players are protected from getting 1-shot by having temporary hitpoints ('armor points' that refresh every turn). Any time Armor Points are hit, a weapon deals its "hitting armor damage".
- If all Armor Points are used up from taking damage then a weapon deals its "full damage".
- Reduced complexity of edge cases.
- Reduced complexity of armor system (less variables).
- More likely to be immune to some damage with enough APs; there is no way to miss armor.
- Auto weapons might be more lethal because it's harder to become immune to their high damage.
- Combat might be faster because there are less calculations and knowledge required to understand the armor system.

Regardless of design choice, we can:
- Potentially reduced complexity of auto/burst miss chance penalties. (We could standardize all auto/burst miss chance penalties, with some exceptions. Thataway, we have less variables to write down per weapon.)

I listed out some of these thoughts in tabular form:

![image](https://user-images.githubusercontent.com/2192156/33624730-2813a39a-d9aa-11e7-9d65-48ac25745bb3.png)

What do ya'll think? And I understand that we may just need to play C2.0 for a while.

**Comment by 1sourcecontrol** [comment]
I had another thought! Hopefully a stroke of genius? 
Implementation 3:
- Always 100% armor coverage. (prevents players from getting one-shot/prevents us from having to make jenky rules to prevent one-shots)
- Weaker armor rigs (like light and recon) or armor rigs with only a chest rig will always allow a certain amount of damage through armor.
 - Keep Armor Piercing Level (APL)
- Keep Armor Points (APs)

![image](https://user-images.githubusercontent.com/2192156/33728391-21eb794e-db2f-11e7-9b8b-7d642f68d0a5.png)

Compared to the current implementation of C2.0, this would reduce complexity by:
1. Eliminating rules for hitting or missing armor.
- Right now, we have like, 4+ hit/miss rules that players have to know to properly use armor.
2. Remove armor rolls (we will already be rolling more on-average with the new weapons)
3. Standardize getting damaged through armor as a rule rather than an exception. 
- This will help keep people from being invulnerable if there is no armor roll. It turns out, if you aren't wearing armor that covers every square inch of your body and you get shot with enough bullets all over the place, you die! 
4. No changes _required_ for existing weapons.

Other note, I probably should do a little rebalancing of Armor Piercing Level, regardless of if we do these changes. My original plan for APL changed halfway through development and it probably should be rethought and refined a little more.

**Comment by 1sourcecontrol** [comment]
I apologize for making more to read. But this is basically a TL;DR in the hopes that I can bring more clarity to all these details.

To compare the (what I consider) best ideas, I tried to contrast them.
Before we get to that, they fundamentally have:
- No rules needed for armor coverage. No edge cases introduced by armor coverage.

### Redesign 2

Weapons
- 2 contextual dmgs per weapon

Armor
- Potential for shotguns/automatics to get through armor and do tremendous damage but this is somewhat mitigated by the introduction of the contextual  "armor damage" (damage done when armor is hit)
- Harder to balance. Damages need to be fine tuned and there may frequent occurrence of these two extremes: always being susceptible to damage or being completely invulnerable
- Simplest implementation; No Damage Allowance math.
- Might be the easiest for players to learn.
- More Design Time: most ranged weapons will need to gain a second damage, and AP level will need to be removed.

### Redesign 3

Weapons
- 1 dmg per weapon
- AP level per weapon

Armor
- AP Level increased by armor plate   level
- 1 to 2 rules added for damage   allowance
- Damage allowance decreased by using   better rigs or more rigs
- Depending on how we design with damage allowance, It may be impossible for characters to be   invulnerable unless you are in full armor. Enough lower level enemies could whittle   you down and kill you, no matter your level*.
- Probably easier to develop; 1 damage   and 1 APL VS. 2 contextual damages.
- ~~Less Design Time: Only armor systems and armor rules needs to change.~~


*Of course, we can design in the ability for higher level armors/rigs to remove damage allowance. We could design in a tradeoff of reduced Damage Allowance at the expense of APL. This will dramatically increase your potential for 100% invulnerability to lower level weapons or pistols/smgs while increasing your vulnerability to higher level weapons or rifles/long rifles.

**Comment by 1sourcecontrol** [comment]
Is this too low on the priority list? I'm chomping at the bit to hear back. 
_Heh, I'll probably hear back after ya'll use C2.0 combat. Hopefully it doesn't have too many rough edges_

**Comment by bleehu** [comment]
Didn't mean for this to get so stale. You predicted my response pretty well; I'm nervous about changing anything further until we do some tests.

The added complexity of now having two damages to weapons for redesign 2 makes me very uneasy. Weapons are already cumbersomely complex as they are. I'm still re-reading all of this literature on redesign 3 to try to understand it.

Also thought you didn't want to hear back? I thought you were on break?

**Comment by 1sourcecontrol** [comment]
Fair enough. I am beginning to see more value in testing -- as my thoughts waffle all over the place with no well-tested ground to base my reasoning on. I can only guess where the problems are.

Assuming I know what you're hung up on,
I'll try to boil down redesign 3 a little. The bottom line is, redesign 3 keeps C2.0 as it is but removes armor rolls and allows guns to (_almost_) always do some damage no matter the strength of your armor (damage allowance).

Oop, what I meant was, I was hoping there would be replies waiting for me when I came back. And I'm definitely eager to hear all ya'lls thoughts. _(I'm back now!11)_

**Comment by bleehu** [comment]
https://www.bing.com/images/search?view=detailV2&ccid=jd91B8gW&id=6961731301F511606F3D095798F1F4FEBBDFB127&thid=OIP.jd91B8gWYFiPIKMR5M0OQQHaGC&mediaurl=http%3a%2f%2ffc09.deviantart.net%2ffs17%2fi%2f2007%2f194%2fd%2f8%2fACDC_BACK_IN_BLACK_by_JackDrown.jpg&exph=489&expw=600&q=back+in+black&simid=607996418588544346&selectedIndex=9

**Comment by bleehu** [comment]
Welcome back! We missed you!

redesign 3 sounds really interesting to me. Can you make a PR with the specifics?

**Comment by 1sourcecontrol** [comment]
Thank you!

I can definitely put something up, when I can.

**Comment by bleehu** [comment]
Closing this out as Won't-Do; stale
