### ISSUE TITLE
Styledguide Conformity w/ "Description" & newlines

### ISSUE THREAD

**Issue by 1sourcecontrol** [trowl223/Compound_X#247]
#244 
@bleehu and I need to discuss:
-  Removing/homogenizing "Description:" & "Description/Notes:" 
- How do we handle newlines at the end of a stat block? (Multiple lines after a stat declaration?)

**Comment by bleehu** [comment]
Is this an issue with Compound X or an issue with our styleguide? If it's the latter, lets break this into two separate issues on the design repo, that way we can stay focused on each of the two goals.

**Comment by 1sourcecontrol** [comment]
Uh, well, I think it's both?.. We need to know how to properly style so that we can know how to proceed with editing CX text docs.
