### ISSUE TITLE
Creature/Character Sizes

### ISSUE THREAD

**Issue by Reveraine** [trowl223/Compound_X#253]
As I'm going through the race rework, I've noticed we don't have rules pertaining to sizes, even though sizes exist. 
It is my opinion that size should not affect combat, for fear of making it too complex, but rather influence puzzles, traverse-able spaces, and role-playing(perhaps intimidate/persuade).

So far, we have:
Small: 3'5"-5". 85-130lbs
Medium: 5'1"-6'2". 110-230?lbs
Large: 6'3"-7'5". 180-400lbs

These numbers are subject to change, but initially they were designed to keep a wide size range while making it seem plausible that they all have access to the same weapons.

Related, we don't seem to have particular rules for weight. They could be based on strength, or they could be a combination of strength and body weight. I think currently it's a straight strength check, which we could keep, if we like them, but it might be helpful to have encumbrance rules. Something like if you carry X percent of your body weight for X turns, you become exhausted.

**Comment by 1sourcecontrol** [comment]
Sounds interesting! I like the idea of introducing a standard for the body sizes w/ body weights.

I think it would be fair to add some encumbrance rules. I hope that they would be quite easy to gauge, to keep the complexity down. Maybe a formula like 20*STR = weight lifted in pounds for 5 turns. I think it might be ill-advised to make encumbrance a function of character weight, or min-maxers like me will have no downside to maximizing my weight. (Btw I'm not aware of any encumbrance rules besides a given STR check.)

Side note, it is kinda goofy that we're using metric (meters) and US standards everywhere else. Maybe we should decide one way or another?

**Comment by Reveraine** [comment]
@1sourcecontrol 

I thought of min/maxers as well, though I did not have a solution.

Yes. I don't mind converting them before they go into the rules, but as I conceptualize things it's easier for me to write them in Imperial.

**Comment by bleehu** [comment]
I kinda like the potential for restrictions on "if you carry Sir Andres for 4 turns, you are now exhausted and he has to use his actions to move himself." While fun, that particular scenario felt pretty gamey to me. 

Rev and I talked IRL about the potential complexity bloom here around the mechanical side of this feature and I wanted to capture some of that here. It would be awesome if we could support radically different body types; it's also a little game-y that  all of our alien races happen to be about human-sized. But it prevents us from having to recalculate different hit chances, acrobatics mechanics and what weapons and armor each different sized alien or entity can use, which would be a herculean lift for our team especially as we try to push the scope into the level 10+ territory. The proposition that Rev has listed up top here I feel is a good compromise between adding some variety and detail, without being too complex.

**Comment by 1sourcecontrol** [comment]
>While fun, that particular scenario felt pretty gamey to me.

Side note on this, CX could use some physical description of CX's robot races. I.e., do the robots use hydraulic cylinders, electric-muscle fibers, or electric motors? From the technology I run into in my job, electric motors or hydraulic cylinders do not get 'tired' or 'exhausted'. Depending on the design, a robotic arm can hold that weight indefinitely as the other axes of the robot move around. _But we can also ignore that realism, heh_

**Comment by 1sourcecontrol** [comment]
Oh, and on the other thing you talked about @bleehu:

>"...alien races happen to be about human-sized. But it prevents us from having to recalculate different hit chances, acrobatics mechanics and what weapons and armor each different sized alien or entity can use..."

It would be a low-development-cost addition to make racial traits/characteristics that emphasize different race dimensions. For example, maybe purchasing armor costs 10% more due to the need to customize armor shape for an Opalite due to their fish-bodehs. Or perhaps the race has a bonus to be hit due to the race's large size (like a large rock monster).

Whatcha think?

**Comment by bleehu** [comment]
It seems to me that this thread is showing up in the new races work that @Reveraine and Rose are doing. Can we close this? Was the question answered?

**Comment by Reveraine** [comment]
The question was answered, but we still need the rules written. We've been putting sizes in, but don't actually have a definition for what they mean. That is something that doesn't have to be determined by me, necessarily.

**Comment by Turtlelord26** [comment]
Is this part of the Species rework or is it a new project?

**Comment by bleehu** [comment]
I believe each species now lists a size. This isn't used anywhere though.

**Comment by Turtlelord26** [comment]
Making it used places sounds like a new project that shouldn't hold up species rework

**Comment by bleehu** [comment]
Shipped in new species rework https://github.com/bleehu/Compound_X/pull/519
