### ISSUE TITLE
Misc additions to the Glossary

### ISSUE THREAD

**Issue by 1sourcecontrol** [trowl223/Compound_X#254]
Hard Point, Shield Upkeep, Shield Strength and Armor Strength need to be added to the Glossary. (These are all explained in the armor doc and/or basic rules doc.)

**Comment by bleehu** [comment]
Added some in #301 but want to make sure we know if we're keeping Shield Strength/Armor Strength for sure before adding them.

**Comment by bleehu** [comment]
@dfuchs2 Can you tackle this one too?

**Comment by dfuchs2** [comment]
I'll check everything out when I get back to my computer.

**Comment by dfuchs2** [comment]
About Shield Upkeep, is that a now-unused term? I assume it refers to shield recharge rate, but the term "Shield Upkeep" doesn't appear to be used anywhere other than here (unless I've overlooked something).

**Comment by bleehu** [comment]
That's a good question! @Turtlelord26, did you abolish Shield upkeep in later updates to shields?

**Comment by Turtlelord26** [comment]
Nope, shield upkeep still exists. It's a per-turn cost to maintain it. Used to be called nanite upkeep, so I changed it to energy upkeep, which is probably how it managed to hide. Shield upkeep might actually be a better word for it.

**Comment by dfuchs2** [comment]
I'm still not entirely clear on shield upkeep. Is it an energy cost to recharging shields? I haven't seen any documentation anywhere related to shields that refers to it.

**Comment by Turtlelord26** [comment]
Reading now, I also concur that shields do not appear to have an upkeep. None of the item entries have such a stat specified. I am not sure what I was looking at before, but it was probably cloaking modules.

**Comment by dfuchs2** [comment]
Is there anything else to do here, or should this one be closed? I got the other rules added in.

**Comment by Turtlelord26** [comment]
Throw it in the fire!
