### ISSUE TITLE
Replace Nanite Restore Doctor Procedure

### ISSUE THREAD

**Issue by bleehu** [trowl223/Compound_X#262]
The existing nanite restore ability is out of aesthetic with the rest of what the doctor can do and needs to be replaced with a more appropriate ability.

**Comment by Turtlelord26** [comment]
I wonder if a Doctor could be able to 'Nanite Restore' the new medical nanites...

**Comment by bleehu** [comment]
Perhaps. Either way, it's an artifact of old nanites, and wasn't well-balanced even at the time.

**Comment by Turtlelord26** [comment]
I think I want to try enabling that function. It might become a balance nightmare and have to be yanked, but we won't know that unless we try. Similar logic for #613 replacing the nanite pack instead of deleting it entirely. Implementation soon.
