### ISSUE TITLE
Need New Doctor Attack Procedure To Replace Pasteurize

### ISSUE THREAD

**Issue by Turtlelord26** [trowl223/Compound_X#264]
Pasteurize exists as a node in the tree, just above Harmacist Spike, but has no entry in the descriptions document.

**Comment by bleehu** [comment]
Needs to be replaced by a new attack power; pasteurize as it was written is out of aesthetic.

**Comment by bleehu** [comment]
Need to finish merging PR #668 so that we don't overwrite the binary image file for the doctor procedure tree; binary files cannot be combined in git.

**Comment by bleehu** [comment]
Closing as done.
