### ISSUE TITLE
Gripe - Secondary Stat Info

### ISSUE THREAD

**Issue by Reveraine** [trowl223/Compound_X#269]
The paragraphs in basic rules describing how secondary stats work (line 169) and what they do (line 344) are unclear due to the separation. This becomes a problem when understanding armor movement speed.

**Comment by 1sourcecontrol** [comment]
I'm not sure how to solve this and not rabbit trail the writing. @Reveraine would it be enough to add a reference to where the "what they do (line 344)" is?

Open to suggestions.

**Comment by bleehu** [comment]
Rev may not know; she was the designated "griper" for the play session. So any time there was a problem, she wrote it down. 

Maybe a reference at the bottom of the section from line 169 to the section in line 344 would work?

**Comment by 1sourcecontrol** [comment]
Ahh, okay.

Sounds like a good start to me! (or hopefully a good ending solution)

**Comment by Turtlelord26** [comment]
Have we fixed this? @bleehu

**Comment by bleehu** [comment]
@Reveraine, Is the work in PR #638 sufficient re-wording to make carry capacity legible?

**Comment by Reveraine** [comment]
Yep! Looks good to me!
