### ISSUE TITLE
intercept feat (feat from my adept with the chain)

### ISSUE THREAD

**Issue by Wildlovelies** [trowl223/Compound_X#27]
Reaction feat for tanks,
move half of your movement speed, if you end up between an ally and its attacker, intercept the attack
Tank loses one action from their next turn. can only be used once per round.

**Comment by trowl223** [comment]
Ideas should be discussed elsewhere, not on the issues page. PM me and we'll chat about this feat : )

**Comment by bleehu** [comment]
It's fairly common practice to submit an issue and use the label "Feature Request" for ideas that people have that they want to submit. @trowl223
