### ISSUE TITLE
Gripes - Needed for Dev Meeting

### ISSUE THREAD

**Issue by Reveraine** [trowl223/Compound_X#274]
Rolling d10's vs 2d10's.
How weapon skill feats work with the new system.
Having decimals for feats and attachments rather than combinations with whole numbers.

**Comment by 1sourcecontrol** [comment]
Someone will have to fill me in on these details, since I'll be missing the dev meeting. 

plez

**Comment by bleehu** [comment]
That dev meeting will likely wait for you, since it specifically has to do with confusion around playing C2.0 as written.

**Comment by 1sourcecontrol** [comment]
Oh, okay. Hopefully we can do that soon.

**Comment by Turtlelord26** [comment]
Closed in dev discussion.
