### ISSUE TITLE
Shadowy Assassin Class Feat

### ISSUE THREAD

**Issue by Turtlelord26** [trowl223/Compound_X#29]
Because it does not specify melee attack, here is a thing I think you can do:

1. Take hunter class for proficiencies in long arms and cloaks (and cheaper cloaking activation)
2. Cross-Train feat, take Shadowy Assassin from the assassin class
3. Be on the outskirts of a fight and behind cover to reduce the likelihood of direct observation and so maintain your cloak despite attacking for several rounds per combat even at low level.
4. Revel in your auto-critting sniper glory

Is this interaction intended?

**Comment by trowl223** [comment]
Definitely not intended, nice find. I'll be patching the feat to specify Melee attacks.

**Comment by Wildlovelies** [comment]
I believe stealth also ups crit chance, so just cloaking should give you a similar effect, unless this has been removed

**Comment by bleehu** [comment]
@trowl223 It's been a couple of months. You got this or you want me to reassign it?

**Comment by trowl223** [comment]
Yes please, thank you.

**Comment by bleehu** [comment]
merged and completed!
