### ISSUE TITLE
Race Document File Structure

### ISSUE THREAD

**Issue by bleehu** [trowl223/Compound_X#295]
In Rev's recent pull containing the new Tundari work, she split the new class out into a sub-file. We need to either split the rest of the classes out into their own files and delete the redundancies in the original file 
or
merge the work in the new file into the original races document. 

The solutions are pretty much equal from a performance perspective. I have a slight preference for using all the same races document which requires a few lines less code in CXDocs, but those are very easy lines to write if we'd prefer to break it up.

**Comment by 1sourcecontrol** [comment]
I think I'd prefer to have it all in one doc, so I don't have to bounce around to different files.
