### ISSUE TITLE
Feature Request: Human Homeworld Section

### ISSUE THREAD

**Issue by bleehu** [trowl223/Compound_X#298]
As we are adding cool new stuff to our cool new races, could we backfill some flavor for the old races to maintain equivalence? Specifically, could we add a blurb about the Human Homeworld similar to the sections we've added on the Opalite and Tundari homeworlds?

**Comment by bleehu** [comment]
Assigning to Rev for now. Feel free to send it to Shrub or Rose if Rev is bogged down.

**Comment by Reveraine** [comment]
So this is all happening one at a time. They are already being included in the race rework, for all of the related issues. They don't need to be backfilled, as such because they won't get merged to play until they're all done. So, use the old rae documents until all the new ones are up.

**Comment by bleehu** [comment]
You don't think it's easier to break the work up into smaller chunks that fit into a sprint better and get reviewed separately?

**Comment by Reveraine** [comment]
I don't think so, no, but I'm also not the one doing the reviewing.

**Comment by 1sourcecontrol** [comment]
Flavor text will be easier for me to review than mechanics since I don't have much to do with it. So as reviews go, I think it won't be too bad.
Not like the Dev -> RC -> Play pull requests. Those are pretty gargantuan. *hint hint* *can we make versions more often so I don't have to review as much at one time? @bleehu*

**Comment by bleehu** [comment]
I'll start doing them every sprint.

**Comment by 1sourcecontrol** [comment]
Sounds good! If that is more of a burdensome task than you want to deal with, feel free to go every other sprint or whatever makes sense.

**Comment by bleehu** [comment]
This was moved to the GM guide
