### ISSUE TITLE
Summon Tentacles Still needs update

### ISSUE THREAD

**Issue by bleehu** [trowl223/Compound_X#3]
None of the discussed changes have been made to Summon Tentacles warlock power.

**Comment by trowl223** [comment]
Fixed. Also created second level of the spell which deals necrotic damage to grappled opponents.

**Comment by bleehu** [comment]
Awesome! =D

**Comment by bleehu** [comment]
Tentacles _still_ not patched in play.

**Comment by trowl223** [comment]
Added in
