### ISSUE TITLE
Rolling the Average

### ISSUE THREAD

**Issue by 1sourcecontrol** [trowl223/Compound_X#312]
Looking for clarification and a little textual improvement.

(I can't"@" Rev, @bleehu halp what is happening?) Reveraine, when you wrote "2d10" under the "Rolling the Average" did you mean to take the average of 2d100 rolls? Or was it for 2d10 combat rolls?
Also, did you mean for "Rolling the Average" to automatically prevent critical fails/successes? 
Or did you just mean that rolling an average value will significantly reduce the chances of critical fails/successes?

Pending Reveraines's responses, I think the writing should be clarified so that the aforementioned questions will be answered. (The issue is open for anyone to do this if they want to. I may take it up, if I have the time)

**Comment by bleehu** [comment]
I'm not sure what's going on there. I Can @Reveraine just fine? I believe the intention was to take the average of two rolls of 2d10, where the 2d10 are used in lieu of 1d100.

**Comment by Reveraine** [comment]
That was my original intention, yes. However, as mechanic's lead, feel free to change the wording/actuality of the definition to fit/balance the game.

**Comment by bleehu** [comment]
@1sourcecontrol can we assign this to you to reword and make a PR?

**Comment by 1sourcecontrol** [comment]
Huh, now I can '@'. Idk what that was about.

Thanks Rev/Bleehu. 

@bleehu , sure, I'll take it.
