### ISSUE TITLE
Renaming "silenced" to be aesthetically compliant

### ISSUE THREAD

**Issue by 1sourcecontrol** [trowl223/Compound_X#316]
https://github.com/bleehu/Compound_X/blob/973ff5fc803ba781bbc6c0171580a829b991bdc5/CharacterCreation/Class-Specific%20Documentation/Doctor%20Procedures.txt#L328

https://github.com/bleehu/Compound_X/blob/973ff5fc803ba781bbc6c0171580a829b991bdc5/CharacterCreation/Class-Specific%20Documentation/Doctor%20Procedures.txt#L330

While the term is common in fantasy games, I think it doesn't fit our lore.

Turtle suggested "stifled", I'm more for an explicit "Nanite Impairment" or "Nanite Disrupted/tion"

**Comment by 1sourcecontrol** [comment]
I think we should add a status affect if anyone thinks this might be used in other abilities. I could certainly see this getting used as a status effect on special bullets.

**Comment by Turtlelord26** [comment]
This is probably blocked by the resource discussion, as it will be hard to name our silence effect without a solid foundation for what it's silencing.
(if someone disagrees and has progress to submit feel free to nix the blocked tag)

**Comment by 1sourcecontrol** [comment]
I looked all over the place - I thought we had an issue for the resource discussion- I'll go ahead and make one so we can track progress on github

**Comment by 1sourcecontrol** [comment]
#317
