### ISSUE TITLE
Resource Discussion

### ISSUE THREAD

**Issue by 1sourcecontrol** [trowl223/Compound_X#317]
*I'd like to have some or all of the resource discussion on here, to track progress. (I couldn't find another issue that actually talks about this, maybe we just did it in person?)*

Correct me if I'm wrong, I believe we had arrived at *(I added some points for thought)*:
1. Nanites still being the overarching generic resource for CX.
2. Nanites would be buyable as purpose built packs.  Standard Nanites regenerate with the character. *(From the characters own body resources?)*
3. Hackers can hack Nanites to alter their performance/function
4. Nanites are not flowing in someone's body as in the Trowl era -- if they aren't -- then how are they located on someone? An arm-band that contains them?
5. There are other resource bars used, on a class by class basis. (Such as needles for the doctor class)

**Comment by bleehu** [comment]
👍 on all points.
If an armband or something is what we're going with, we should put a note that every class starts with that equipment and that it can be taken away.

**Comment by Turtlelord26** [comment]
I also want a whiteboard for this discussion.

**Comment by 1sourcecontrol** [comment]
I like the visual of an armband ... sleek, streamlined, non-obtrusive..
But I haven't the foggiest idea of how a human (or w/e race) will control the Nanites in our current setup. 
Would the armband be sensing nerve impulses, to be controlled? That can be done in the real world on the surface of the arm, I believe.

*edit* and if the Nanites are regenerated by using resources on a person's body, then there has to be some sort of interface to the human body. Maybe the armband has some small -flexible- I.V.s that it plops into the arm, after the armband is attached? 

Since I'm out of town, what can we do to move on with this discussion? I'm free to talk on weekend mornings or friday/saturday evenings ... but not afternoons.

*granting that all this is pending creative's thoughts*

**Comment by bleehu** [comment]
@Turtlelord26, @Reveraine, can we close this since it basically led to https://github.com/bleehu/Compound_X/projects/18?

**Comment by Turtlelord26** [comment]
Yes
