### ISSUE TITLE
Need separate Monster Manual, GM guide and Design Spec Repos

### ISSUE THREAD

**Issue by bleehu** [trowl223/Compound_X#32]
Monster Manual - official rendering of the beastiary from CXDocs, analogue to DnD monster manual.

GM guide - Tips and tricks for those running the game, maybe even a short official adventure. Mashup of DnD GM guide and Phandelver starter guide

Design spec - Director-level design specifications for how to make things for CX and how not to break it.

**Comment by bleehu** [comment]
@trowl223 Do you have this taken care of? Or should I make these in the private repo account that I pay for?

**Comment by trowl223** [comment]
It might be a better idea to make them in a private repo, as they'll have publication-ready material eventually.

**Comment by bleehu** [comment]
check your inboxes for invites to the following private repos. @1sourcecontrol @trowl223 @Wildlovelies

https://github.com/bleehu/CX_Galaxy_Masters_Guide

https://github.com/bleehu/cxBeastiary

https://github.com/bleehu/CX_Design_Guide
