### ISSUE TITLE
Createing a character: Player stats

### ISSUE THREAD

**Issue by Masterdiekillsu** [trowl223/Compound_X#33]
I looked on the CX Docs page in the basic rules section, but no where does it say how many points of stats a character is allowed to have total. It would be helpful if this number was indicated somewhere, instead of having to guess based off of the character sheet PDF. 
EX: all of the points on the sheet add up to 35, is that the maximum amount of points you are allowed to have?

**Comment by 1sourcecontrol** [comment]
I think it's listed in the races sheet, because the skill points vary between races

**Comment by bleehu** [comment]
It is not. 
Cyborgs are listed as having a 40 point starting pool, and humans are listed as having +2, but it doesn't actually say anywhere what the baseline is.

**Comment by Masterdiekillsu** [comment]
The main problem here would be making a character using only the webpage. When picking out a race and trying to know how many stats the character should have, it doesnt say anywhere on the page. This is the webpage BTW. I'll gladly check to see if its in the Github notes somewhere, and if it is, do you think you could update the webpage about that Blee? If you want to could write something that explains how it works (if I find it) so that all you have to do is copy and paste.

**Comment by bleehu** [comment]
This is the git repo for the compound X Core rules. For issues regarding the web page, go to https://github.com/bleehu/cxdocs/issues
That said, it's also a major flaw with the core rules that we don't state this anywhere in the core rules for it to trickle down to the website.

**Comment by trowl223** [comment]
Just as a note so its recorded somewhere on this site for future reference:
42 for humans
40 for all other species. Some species may have less than 40 depending on starting abilities. Keep in mind for future race builds, lose two stat points is a -8% debuff, but it applies to many different skills so it has greater value than a base -8% debuff. Alien racial abilities must be balanced with that higher-weight debuff in mind.

**Comment by bleehu** [comment]
*twitching eye* Don't write it here! *voice cracks* write a patch. Or direct someone to write what you've put there.

**Comment by bleehu** [comment]
I'm greenlighting this and taking it myself.
