### ISSUE TITLE
Gripes - Nanite functions

### ISSUE THREAD

**Issue by Reveraine** [trowl223/Compound_X#337]
There is no specificity to Nanites currently.
(I think this will get pooled in with the resource discussion.

**Comment by bleehu** [comment]
At the risk of sounding meta, can you be a little more specific? Is the problem that we don't know what nanites can and cannot do?

**Comment by rosebrallier** [comment]
I think so. Lets try to hash this out in person?

**Comment by rosebrallier** [comment]
Can we close this issue given our consensus on [Project 18](https://github.com/bleehu/Compound_X/projects/18)?
