### ISSUE TITLE
Gripes - Acrobatics documentation

### ISSUE THREAD

**Issue by Reveraine** [trowl223/Compound_X#340]
There is a lack of specific acrobatics documentation.

**Comment by 1sourcecontrol** [comment]
@bleehu @Turtlelord26 
Would it make sense for us to define it in the skills doc?
Seems to me we wouldn't need much more than 2 paragraphs worth of words?

**Comment by bleehu** [comment]
I'd like to hold out on this to see if we can have Z take it when he's over his fever and hopefully doing more work on the project.

**Comment by bleehu** [comment]
@rosebrallier, do you mind taking this in light of Zach's retirement?

**Comment by rosebrallier** [comment]
Not at all!
