### ISSUE TITLE
Race Rework; Plan of Action

### ISSUE THREAD

**Issue by 1sourcecontrol** [trowl223/Compound_X#343]
From our past dev meetings, I think we talked about/agreed upon how the technical design would go. But either I remember it differently than it's currently being implemented or I forgot the specifics. This issue was made to define the specifics.
From what I remember, the race (now, soon to be called 'species'?) rework was going to consist of 3 things:

1. Races
i. Picking a race would come with certain benefit and/or malus traits (defined by that race). 
2. Subraces
i. Add/Remove new benefits/malus traits to the Race
3. Trait pool
i. A reasonably sized (idk, at least 8 traits?) pool that you can pick X number from after picking a race and subrace. 
ii.  The same trait pool is available to all creatures from that race.

This is how I remember it.... How do you?

 (P.S. I'm not suggesting the rework has to happen the way I remember it; I just want to clearly define what's happening and make sure we're all on the same page)

**Comment by Reveraine** [comment]
That is close to what is happening, yes. 
With the exception that subraces in general have access to trait pools not available to every sub-species. There is also a general species trait pool that everyone in the species can access.

**Comment by 1sourcecontrol** [comment]
Ok, cool! Thanks

**Comment by bleehu** [comment]
Was this question answered? Can we close it?
