### ISSUE TITLE
Skill point limiting by level

### ISSUE THREAD

**Issue by Turtlelord26** [trowl223/Compound_X#344]
Currently it is possible for a level 3 character with 10+ int/cha to have one maxed out skill. This has unfortunate implications for dungeon design and is dubiously realistic. Propose a limit on skill points per level in addition to the global cap. For example, if we wanted to say that a character can max out skills at level 10, then the point cap would be 6 per level, up to 60.

**Comment by bleehu** [comment]
Assigning to @rosebrallier, who has accepted ownership of the skills system.

**Comment by rosebrallier** [comment]
So I went with 5, but 6 is a nicer number. I'll run-through implementing the diff number Soon(tm).
