### ISSUE TITLE
Feature Consideration: Consolidate Melee "blunt" damage subtype and Internal damage type

### ISSUE THREAD

**Issue by Turtlelord26** [trowl223/Compound_X#362]
As the blunt damage is described as bypassing armor, and in fact blunt force trauma causes internal damage.

**Comment by bleehu** [comment]
I think it's a very good idea to keep on the lookout for ways to reduce complexity. In that regard, I applaud Turtle's attention being paid to the opportunity to reduce redundant effects. That is awesome. 

But in this specific case, I think it doesn't make sense to combine blunt damage with internal damage. To explain, i'd like to offer a counterexample. Let's say we're doing damage to a robot wearing heavy armor. If you give that robot a nasty termite-like mechanical parasite that crawls between his armor plates and starts eating up his innards, that damage is internal and is entirely independent of armor type and class. On the other hand, if you take a pipe, baseball bat or sledgehammer and whack the robot with it, the heavy armor probably won't stop all of the damage (as it would if you'd shot at him), but the armor would act similar to a football player's pads and absorb some of the melee damage.

**Comment by Turtlelord26** [comment]
Counterexample accepted and sufficient for mathematical disproof of my conjecture.

**Comment by bleehu** [comment]
Perhaps ye could use smaller words, we are but humble pirates here.
![image](https://user-images.githubusercontent.com/13957025/37693004-d93c0230-2c79-11e8-83aa-5844f6fd7e78.png)

**Comment by bleehu** [comment]
(joking, of course)
