### ISSUE TITLE
Melee 2.1 Part 1: Skill Modifier Strip

### ISSUE THREAD

**Issue by Turtlelord26** [trowl223/Compound_X#363]
See #356 

We need to remove the references to melee combat skills from melee attack and Guard calculations. Said calculations will need to be reformulated to compensate.
A melee attack should not be significantly more complex than a ranged attack.
The Guard Class should be as simple as feasible.

**Comment by bleehu** [comment]
@Turtlelord26  What is "Guard Class"?

**Comment by Turtlelord26** [comment]
Just Guard DC with the D removed. I don't really like using the DC abbreviation in both combat and skills/saves, the areas are pretty disparate.

**Comment by Turtlelord26** [comment]
Progress mark: Skill modifier removed from calculation by PR #432, but GC has not yet been rebalanced to compensate.

**Comment by Turtlelord26** [comment]
Finished in #490
