### ISSUE TITLE
Weapon Proposal: Staff-sling

### ISSUE THREAD

**Issue by Turtlelord26** [trowl223/Compound_X#369]
It's like a sling, but gigantic. Probably requires very high Dex to use, can load with bullets (which means lead lumps) or grenades.

More normal slings also includeable.

**Comment by bleehu** [comment]
Like this? https://en.wikipedia.org/wiki/Sling_(weapon)#Staff_sling It seems a little... niche? Maybe a house-ruled weapon?

**Comment by Turtlelord26** [comment]
It is a little niche, but it has the advantage of requiring almost no tech base to build and use.
Maybe we sneak into our very very long range planning a low-tech rim-world supplemental rulebook? (and in that case, close this issue)

**Comment by bleehu** [comment]
Sure.
