### ISSUE TITLE
Feature Consideration: New Save - Awareness

### ISSUE THREAD

**Issue by Turtlelord26** [trowl223/Compound_X#370]
The thought is to move passive perception from the awareness *skill* to a new awareness *save*, which is more in line with skills being a thing you actively do vs saves being a response to outside stimuli. The other perceptual skills, spotting and investigation, remain skills.

An initial proposal is to calculate the Awareness save like the other saves, but based on the PER and LUC attributes. I like this for two reasons. One, it is good for stat balance (unlike a different proposal, per+int, which dramatically overvalues int in saves) and two, because it introduces a baseline, meaningful penalty for making luck a dump stat.

Technical expects to approve testing such a feature, but first we specifically want input from Opossum, who has been undertaking the skills rework. Since this idea would remove a current skill, we should consult the skills system dev (who I cannot @ here but will poke in slack). I also want thoughts, especially critical thoughts, from everyone else after the idea has had time to mature.

**Comment by bleehu** [comment]
I really like this idea! I like how it lets us roll the save after the fact, rather than having a specific constant passive perception on all the time.

I also approve of the balance shift of using PER and LUC. 

Since Opposum has left the project for now, we can ship it without his input.

**Comment by Reveraine** [comment]
Aprrrroooooove

**Comment by bleehu** [comment]
I think the test went pretty well. @Turtlelord26 and @Masterdiekillsu shipit?

**Comment by Turtlelord26** [comment]
We have a fairly serious balance issue with awareness (a save) contesting stealth (a skill), but that doesn't block a PR to dev as long as we make the Issue. Which I have now done: #382

**Comment by Reveraine** [comment]
Awareness Added
