### ISSUE TITLE
Gripe: Edit Skill Requirements and Class Passives to reflect Systematized Skills

### ISSUE THREAD

**Issue by rosebrallier** [trowl223/Compound_X#372]
For example:
Using grenades requires 10 skill in explosives, which is no feasible in early levels because skill points at lvl1 have decreased by 50.
Pilot passively gives 10 in piloting (a skill which no longer exists).

**Comment by bleehu** [comment]
@rosebrallier can you handle this? Do you have enough familiarity with Git to make it so?

**Comment by rosebrallier** [comment]
This is on my docket after I get reviews and edits on the systematized skills update.

**Comment by rosebrallier** [comment]
Merged or PR'd:
- [Basic Rules](https://github.com/bleehu/Compound_X/pull/432)
- [Classes](https://github.com/bleehu/Compound_X/pull/410)
Still to come:
- Feats
- Weapons Docs

**Comment by rosebrallier** [comment]
Note to self: remember to consistently identify specific skill checks (ie "DC of Athletics checks to break down a door" as opposed to "door-breaking DC")

**Comment by rosebrallier** [comment]
There may be further instances to clean up, but the full repo has been reviewed for skills consistency as of PR #579.
