### ISSUE TITLE
Feature Request: Performance or Art skill

### ISSUE THREAD

**Issue by rosebrallier** [trowl223/Compound_X#375]
We should have a set of Performance or Art skills to use when rolling for a character's artistic endeavors like:

- performing an interpretive dance
- drawing a picture
- singing
- playing a musical instrument
- acting out a Shakespearean soliloquy
- stand-up comedy
- composing a ballad
And much much more!

**Comment by rosebrallier** [comment]
We could also have Performance, where Performance is a general [charisma] skill check that includes the subsets of: persuasion, deception, speech, intimidation.

Art could be a Feat obtained via character backgrounds which gives advantage to a character's rolls in a specific artistic field.

**Comment by Turtlelord26** [comment]
I think that I am partial to having multiple specific skills (and probably letting characters use half of one perform skill to make a check on another) to support more explicit character customization. Backgrounds could contribute by granting proficiency (i.e. class-skill-ness) to a particular subskill.

**Comment by Reveraine** [comment]
I like both of these ideas. 
I think that art could go either way, I am not particularly partial to either with the exception of the simplicity of art as a skill versus adding to our already lengthy feat list.

**Comment by bleehu** [comment]
I think maybe this is symptomatic of a larger issue. When Zach was on the team, he owned skills. Now that he's left, nobody owns skills. Can we at least temporarily let @rosebrallier own it?

**Comment by bleehu** [comment]
@rosebrallier, do you want to take a stab at developing an update to the existing skills?

**Comment by rosebrallier** [comment]
Update to this issue: Skill in Performance has been incorporated into [Systematized Skills](https://github.com/bleehu/Compound_X/blob/dev/CharacterCreation/06_01_Systemized_Skills.txt) with [PR 385](https://github.com/bleehu/Compound_X/pull/385).
Closing this issue since the gripe has been patched, though I plan to address the idea of characters having specific training in a field when I work on backgrounds.
