### ISSUE TITLE
Gripe: Phrasing of "Medicine Saving Throws"

### ISSUE THREAD

**Issue by rosebrallier** [trowl223/Compound_X#376]
https://github.com/bleehu/Compound_X/blob/c3463269fc0d0c8ee2c7f788ba95ccae8a298e3d/01_01_Basic_Rules.txt#L567

Using the title "Medicine Checks" or "Medicine Rolls" would better describe the content of the section, especially since Saving Throws are their own mechanic in the game (and "Medicine" is not one of them).

**Comment by Turtlelord26** [comment]
I'm thinking that that whole section should be looked at and redone (especially that heal skill calculation) as a Hit Point Recovery section that includes rules for healing over time via rest and includes the Doctor class only by way of mentioning that they have alternative means of healing people.

It also might live more happily in a different location of the rules.

Related: The current "Resting" section is no longer in aesthetic, as it only talks about nanites.
