### ISSUE TITLE
Skill Request: Vehicles (Space)

### ISSUE THREAD

**Issue by Turtlelord26** [trowl223/Compound_X#399]
On the theory that flying in air and flying in nothing are different enough to represent the difference.

**Comment by rosebrallier** [comment]
This is a fair point. For example, while flying in space the enemy's gate is down, which is not the case in air. @bleehu, can I get a greenlight?

**Comment by bleehu** [comment]
I can't change labels on mobile, so please take the comment and I'll update labels later.  You have an explicit green light!

**Comment by rosebrallier** [comment]
TAADAAA
(see [SPACE](https://github.com/bleehu/Compound_X/commit/39319168609e86537bb84a06f2e66e2c5cf67879#diff-eea1936881dbbd3328e36ef9903d9a06))
