### ISSUE TITLE
Feature Request: Skill(General) buff

### ISSUE THREAD

**Issue by Turtlelord26** [trowl223/Compound_X#400]
From #385 

When dealing with progression systems, I always try to aim for maximum end-state power. This involves lots of turtling in RTS and 4X, for analogy. The following concern assumes that mindset is common enough to design around.

I am wary of ever putting points into General skills, because at some point General must become overshadowed by the Specific skills (and if it doesn't we've made a design error because then the specifics have no reason for existing). I wonder if we could mitigate that by having a threshold where having general skill helps your specific skill rolls. Something like having 30/60 points in the General lets you roll the average on a Specific check that you are not using your general score for (including in combat situations), and 60/60 rolls with advantage.

**Comment by rosebrallier** [comment]
This is a cool idea to take into account how in real life, knowing about a General subject makes it easier to approach subsets of that subject (since you have the contextual knowledge and general thinking framework for the field).
What do you think @bleehu ? Useful buff of complexity creep?

**Comment by rosebrallier** [comment]
ping

**Comment by bleehu** [comment]
I'm concerned that's going to make general skills too valuable.  The "wildcard bonus" of being able to use general skills in multiple skill challenges is already a huge equalizer. I'd like to discuss this more,  but I hesitate to write a wall of text. Take it up in person this weekend?

**Comment by Turtlelord26** [comment]
Consensus has been reached that General skills are testable in their current iteration, with the exceptino of Knowledge(General), which shall be nerfed to specify that when a character takes Knowledge(General), they must declare 4 areas of specific knowledge that the General check may apply to, and cannot apply the general check to other specific knowledges.
