### ISSUE TITLE
Feature Request: Hostile Environment Catalog

### ISSUE THREAD

**Issue by Turtlelord26** [trowl223/Compound_X#415]
Because if I'm going to request a feat that requires this feature, I should request this feature too.

Request: A document cataloging hostile environments players may find themselves in, what detrimental effects this has both in combat-scale and at survival-scale, and available countermeasures (like envirosuits, gas masks, etc.) apply, if any.

Terrains may be Bases or Overlays (terms subject to change). A Base terrain is something like Desert, Subfreezing Temperatures, Superboiling temperatures, Vacuum, etc. that a character can only be in one of at a time barring some very unusual DM shenanigans. An Overlay terrain is something like Microgravity, Inconsistent Gravity, Low Oxygen, Airborne Toxins, Smoke, etc. that a character could be in multiple of at the same time (or none). A character does not have to be in a hostile base terrain to suffer from a hostile overlay terrain.

It might be tempting to lable derelict ship as a base terrain, but I think it's more appropriate to model it as multiple overlays depending on exactly what's wrong with the ship.

Complexity note: obviously adds complexity but in a pretty decent way because a given DM is free to avoid any or all of these.

Miscellaneous note: I will generate a combat-scale effect for Inconsistent Gravity as part of my work on GravTech, so whoever takes on this feat doesn't need to come up with that one.

**Comment by bleehu** [comment]
@Turtlelord26, can you turn this into a project plan in the design repo, and if implemented, I think this would go into the Galaxy Master's Guide?

**Comment by Turtlelord26** [comment]
Yes, I think that would be the appropriate place to put it. I'll assume form the lack of notes that no one has too big of a problem with the basic mechanics I proposed, so I'll make that board in design and transplant this issue into the GMG repo.
