### ISSUE TITLE
Dice description

### ISSUE THREAD

**Issue by rosebrallier** [trowl223/Compound_X#429]
https://github.com/bleehu/Compound_X/blob/d310ad25478a7d763dbddeb8129d37a59fc93c66/01_01_Basic_Rules.txt#L34-L35
Do we want to update this to reflect how we roll d10 for hitting  and d100 everywhere else?

**Comment by Turtlelord26** [comment]
Yes, I think we do. 
Also, the  "For now, know" seems wrong and out-of-place; maybe that paragraph could be edited to open more neutrally.

**Comment by Masterdiekillsu** [comment]
Which branch would you like me to make the changes to the wording in?

**Comment by Turtlelord26** [comment]
A new one, and PR it to dev.

**Comment by Masterdiekillsu** [comment]
In the new branch I created, I changed the text accordingly. I dont know how to request a review of it though

**Comment by Turtlelord26** [comment]
Make a PR with dev as the Base and your branch as the compare.

**Comment by Masterdiekillsu** [comment]
Pull request has been made. Unfortunately I have to go to class, so I wont know if this issue gets closed or not. I'll keep and eye on it though and see if there's anything more I can do.
