### ISSUE TITLE
Nanites Aesthetic

### ISSUE THREAD

**Issue by rosebrallier** [trowl223/Compound_X#430]
https://github.com/bleehu/Compound_X/blob/d310ad25478a7d763dbddeb8129d37a59fc93c66/01_01_Basic_Rules.txt#L140-L145
We may want to rework this to be a more lore-based.

**Comment by bleehu** [comment]
Why did we close this?

**Comment by Turtlelord26** [comment]
It was eaten by the nanite removal project.
