### ISSUE TITLE
Charisma skill max

### ISSUE THREAD

**Issue by rosebrallier** [trowl223/Compound_X#431]
https://github.com/bleehu/Compound_X/blob/d310ad25478a7d763dbddeb8129d37a59fc93c66/01_01_Basic_Rules.txt#L435-L436
Where is this from and why is it necessary?

**Comment by Turtlelord26** [comment]
As it's part of secondary stat details I assume it's from 1source. I am of the opinion that having a special cha skill cap is unnecessary complexity (and also that you have full control over what the overall cap is as skills owner), but I didn't actually know this was here until now. @bleehu Do you know more?

**Comment by bleehu** [comment]
My hunch is trying to re-value charisma. I agree very much with Turtle that having one of six things that doesn't act like the other is a hard exception to remember.

**Comment by rosebrallier** [comment]
So I can delete it from existence?

**Comment by Turtlelord26** [comment]
Destroy it!

**Comment by 1sourcecontrol** [comment]
I decided to take a glance at CX after quite-some-time.

The skill max was definitely a Charisma-valuing mechanism. Min-maxing away CHA can/could easily be overcome by dumping skill points into "Speech skill" (or whatever the skills are now). Which reduces the gap between a 2 INT - 10 CHA player and a 10 CHA - 2 INT player.

I tried to revalue the primary stats and balance charisma, this was part of the best I could come up with at the time. I hope ya'll came up with something better.

**Comment by 1sourcecontrol** [comment]
I did mention the skill cap in my parting words on Feb 22nd (slack) :P but that is a while ago, so, oh well

**Comment by Turtlelord26** [comment]
There has been a suggestion that would alleviate the min-maxer problem here, though it doesn't buff Cha directly. See #397 if you're curious.

**Comment by 1sourcecontrol** [comment]
Thanks, I did see that. Hopefully that is sufficient -- although it doesn't address the original problem per se (of players minning charisma to some extent because of a disparity in primary stat value) 
I guess I just restated what you said ¯\_(ツ)_/¯

**Comment by Turtlelord26** [comment]
Well, it's also harder to dump points into persuade/deceive to make up for a low Cha now that putting points into skills is rate limited by level.
