### ISSUE TITLE
Repository Reorganization

### ISSUE THREAD

**Issue by Turtlelord26** [trowl223/Compound_X#454]
Many thanks to 1source for helping us realize we've been playing the armor system incorrectly in #384. In the process, though, another issue has been made clear. 1source had to cite rules in two different documents for the same mechanic - we can organize our rules better than that.

I say we 
1. Pull all of the item/weapon documents out of the character creation folder and drop them in a new Items Documents folder.
2. Add a ground rule that item documents *do not contain rules text*. Then move all of the rules text currently in the various item documents to better homes (probably mostly basic rules).
3. Break up basic rules into more than one document. For example, it seems sensible to transfer all of the combat rules into their own document.

This is a project-level task that definitely requires a superbranch so that, when it is finished, we can side-by-side compare the new repo look with the old one before implementing it.

@bleehu Rules organization is your domain I believe, so what do you think?

**Comment by bleehu** [comment]
Very sensible! I'll make a project board! Sounds like maybe a new dev project?

**Comment by Turtlelord26** [comment]
I don't think so. I'd rather have someone already familiar with the rules hacking them apart and putting them back together better.

**Comment by rosebrallier** [comment]
@bleehu and/or @Turtlelord26 Is this resolved?

**Comment by Turtlelord26** [comment]
Not yet, we still need to relocate the rules text from the item documents.
Items 2 and 3 are good now I believe.

**Comment by bleehu** [comment]
It's one of those awkward full-project scope issues that was initially published to see if the project as a whole would get greenlit.

**Comment by bleehu** [comment]
@Turtlelord26 I believe these three have been executed, but there is still work to be done to take rules out of the item docs. Can we open new issues to track that work and retire this one?

**Comment by Turtlelord26** [comment]
Certainly, but I would caution against messing with the melee weapon file until we get Melee 2.1 merged.
