### ISSUE TITLE
Adept shield still boosts armor stats

### ISSUE THREAD

**Issue by Wildlovelies** [trowl223/Compound_X#46]
Trowl223 said he wanted to remove adepts armor buff, which if it stays, with the full armor feat for adepts, that is a lvl 2 with 50 dr with 100% coverage, 60 DR if cyborg...

**Comment by trowl223** [comment]
I don't recall discussing that.

**Comment by bleehu** [comment]
Well then, let's discuss it. Isn't that OP at level 2?

**Comment by Wildlovelies** [comment]
It was the one off mission where I had the Adept with the chain who cross trained paladin for shield, @bleehu almost died...

**Comment by trowl223** [comment]
I remember now. Mostly it was the paladin shield in addition to the Adept shield with armour.

As far as the Adept's own abilities go, I don't see how being a level 2 changes anything, the adept's shield abilities aren't level based.

I think we should yank Adept for the time being. They were meant to be what the paladin became, and I'll need to rework them to find a good niche for them. The idea of the class is basically the tankiness of the paladin, minus automatic rifles, long rifles, and spells.

Verdict: Yank for now until such a time when they have a more distinct role.

**Comment by Wildlovelies** [comment]
no, it was lvl 2 = full armor feat

**Comment by trowl223** [comment]
Please clarify. Do you mean that at level 2 you take the full armour feat with the class? In the future please mention a feat by name rather than just saying "at level two this class has this ability." We are rapidly approaching the point (or have surpassed it, really) where just saying that a class has a certain output potential means nothing because of how many possible feat combinations can be made.

**Comment by Wildlovelies** [comment]
Acquired: Metal Jacket

Prerequisites: Soldier, Engineer, **Adept**, Berserker

Enables the use of Full Armour by the listed classes

Sorry, here is the feat, taken at level 2

**Comment by Wildlovelies** [comment]
plus cyborg and adept shield bonus to dr
