### ISSUE TITLE
max stats at lvl one not listed

### ISSUE THREAD

**Issue by Wildlovelies** [trowl223/Compound_X#47]
more for a note on min maxing, but no where is it stated that 10 is the max you can put non bonus points into so i could dump stat charisma, luck and int and run a 20 strength berserker with a power fist

**Comment by trowl223** [comment]
This is true. Intended rules: Max you can put into any one stat (even after cyborg stat increases) at level one is 10. The maximum for any stat is 15.

**Comment by bleehu** [comment]
Don't write it here! Either put it in the rules or direct someone on the team to write the fix for ya!

**Comment by bleehu** [comment]
I see this fix as a sort of band-aid as opposed to a well-thought-out fix. We will then have the same issues as soon as a character is level 2 that we have now. It also doesn't give the chance to grow more once at higher levels.

**Comment by bleehu** [comment]
Pull Request submitted. Issue will close on acceptance.

**Comment by bleehu** [comment]
Merged. Closing
