### ISSUE TITLE
player skill ratings not listed is basic.text

### ISSUE THREAD

**Issue by Wildlovelies** [trowl223/Compound_X#48]
as in 10 novice 20 adequate and 40 is expert, 

This is to pertain to cyborgs mainly, who have to see an expert to get upgrades, but they are able to become experts with the skill, that number i cannot find in the github play

**Comment by bleehu** [comment]
It sounds like a role playing term, rather than a specific score. Sounds like that would be up to the GM at this point. I think that's an OK level of specificity at this point. @trowl223 do you agree?

**Comment by trowl223** [comment]
Yes, that is meant to refer to an NPC whose sole profession is designing, building and repairing cybernetic enhancements. They may even be a specialist in a certain kind of cybernetics, like optics, or systems, etc.

**Comment by bleehu** [comment]
Close it?

**Comment by Wildlovelies** [comment]
the base matter is still not addressed, where is your rank in something listed?
Like Repair, is 40 repair and expert in this field?
Knowledge nanites at 40 am I an expert?  
Where is this listed? I briefly remember something before but cannot find it now.

**Comment by bleehu** [comment]
There is no rank. It doesn't need to be listed.
Expert = NPC
