### ISSUE TITLE
Misc items description needs to be updated

### ISSUE THREAD

**Issue by Wildlovelies** [trowl223/Compound_X#49]
Currently states: 
Examples of Misc. Items include rope (20m), compass and map, matches, 
flashlight, a single magazine for your gun, flares, etc. These are basically 
items that have an actual use of some sort. $100 each unless otherwise 
specified, 5 free at start.

magazines generally are not $100 each, my opinion it needs updating or removed, feel free delete if you disagree

**Comment by bleehu** [comment]
I totally agree. Will write a patch.

**Comment by trowl223** [comment]
I totally agree as well. This was from the pre-money days of compound_x when players used an Equipment-Point inventory management style to "purchase" items.

**Comment by bleehu** [comment]
You said nice start. Is there more misc items that you want?
