### ISSUE TITLE
Concussive or Explosive Dmg-type Consistency

### ISSUE THREAD

**Issue by rosebrallier** [trowl223/Compound_X#491]
[E5500 Power Fist](https://github.com/bleehu/Compound_X/blob/45eb5e040a9a13c5af37f049a1b2afb27a807153/Items/04_01_Melee_%26_Thrown_Weapons.txt#L164-L176) calls it's damage type "concussive (explosive)".
We need to decide whether to call the overall damage type "concussive" or "explosive", then track down and correct all the instances.
Personally, I prefer "concussive" significantly over "explosive" or the officially listed ["Explosive (concussive)"](https://github.com/bleehu/Compound_X/blob/45eb5e040a9a13c5af37f049a1b2afb27a807153/01_02_Damage_Types_and_Armor_Types.txt#L30-L34) because "concussive" can logically incorporate damage from a broader variety of impacts than "explosive" (which exclusively implies that an explosion -> shock-wave caused the injury).
In the case of the Power Fist (and the "E500 Assisted-Sledgehammer"), calling damage from those weapons "explosive" does not make sense to me. If nothing else, we should change the damage types of the Power Fist and Assisted-Sledgehammer to no longer imply an explosion-based injury (compared to a broader "you got hit with a sh*t-ton of force" injury).

**Comment by rosebrallier** [comment]
@bleehu any objections to folding explosive dmg under broader concussive dmg?

**Comment by bleehu** [comment]
I think @Turtlelord26 and I had a very similar discussion about Blunt damage vs Internal damage vs explosive damage.... I'm getting some pretty serious deja vu. Lemme see if I can track down the issue/discussion.

**Comment by bleehu** [comment]
I swore it was a longer conversation than this, but I think we do a good job of capturing the potential pitfall of folding damage types.  https://github.com/bleehu/Compound_X/issues/362
@Turtlelord26 , correct me if I'm wrong, but we don't actually have blunt damage listed anywhere? If so, I suppose Blunt and Explosive are both folded under Concussive? Which in turn is countered by the Armor Type: Padded? or something?

**Comment by rosebrallier** [comment]
I don't have a strong preference for folding explosive under concussive, but I [STRONGLY](https://en.wiktionary.org/wiki/hill_to_die_on) object to concussive as a _subset_ of explosive (which it currently is re: [Explosives par](https://github.com/bleehu/Compound_X/blob/fe73c4745385c05680e994745292f40093771567/01_04_Damage_Types_and_Armor_Types.txt#L30-L34)).
The primary reference to blunt damage is [here](https://github.com/bleehu/Compound_X/blob/fe73c4745385c05680e994745292f40093771567/01_04_Damage_Types_and_Armor_Types.txt#L36-L42), but that particular paragraph will soon be moot and deleted re Melee 2.1.

The primary cause  of this particular issue is that [Dmg Types Doc](Compound_X/01_04_Damage_Types_and_Armor_Types.txt) refers to [Explosive (concussive)](https://github.com/bleehu/Compound_X/blob/fe73c4745385c05680e994745292f40093771567/01_04_Damage_Types_and_Armor_Types.txt#L31) damage, while the Power Fist and Assisted-Sledgehammer deal [Concussive (explosive)](https://github.com/bleehu/Compound_X/blob/45eb5e040a9a13c5af37f049a1b2afb27a807153/Items/04_01_Melee_%26_Thrown_Weapons.txt#L172) damage which, afaik, doesn't exist anywhere else.

**Comment by Turtlelord26** [comment]
[Evil Grin] I managed to delete blunt damage without folding it into anything else. Instead whatever the melee weapon's native damage type is is what slips past armor under the appropriate circumstances.

As far as I can tell, we only have the one Force/Shockwave Damage but we have two names for it (Minus a couple explosives, all instances of the damage seem to have both words. Does anyone know of an instance where concussive appears alone?). Removing one of them wouldn't be a folding, just a removal of redundancy. I'm fairly confident that the word concussive would encompass all of the required effects, including our C10, adequately. @bleehu Yea/Nay?

**Comment by bleehu** [comment]
Make it so!

**Comment by 1sourcecontrol** [comment]
FYI,

"concussive (explosive)" was to tell the player that the damage falls under explosives -- to bypass armor. While giving it the aesthetic (concussive) of what it physically is.

**Comment by 1sourcecontrol** [comment]
So the emphasis was on the mechanics of where the player can find the rule and use it, vs aesthetic perfection.

**Comment by bleehu** [comment]
https://github.com/bleehu/Compound_X/blob/dev/Items/04_01_Melee_%26_Thrown_Weapons.txt#L134
is referencing this:
https://github.com/bleehu/Compound_X/blob/dev/01_04_Damage_Types_and_Armor_Types.txt#L25
needs to reconcile with 
https://github.com/bleehu/Compound_X/blob/dev/01_02_Combat_Rules.txt#L90

My recommended fix is that we simply remove the concussive part; if being used by a character with 8 Strength, that means that 60 damage is already going through armor every Action, in addition to it's stunning effect.

**Comment by Turtlelord26** [comment]
I have flavor concerns about letting a fist deal explosive damage. Or are you suggesting changing the fist to deal normal ballistic damage? (That would be good by me, coupled with removing the word concussive from the explosive damage type entry.)

**Comment by bleehu** [comment]
I've miss spoken; remove the weird damage explanation altogether and let it deal melee damage like the swords did last night.
