### ISSUE TITLE
Damage-types internal consistency

### ISSUE THREAD

**Issue by rosebrallier** [trowl223/Compound_X#492]
https://github.com/bleehu/Compound_X/blob/45eb5e040a9a13c5af37f049a1b2afb27a807153/01_02_Damage_Types_and_Armor_Types.txt#L5-L6
The list of damage types in the document introduction is not consistent with the proceeding list of detailed damage types. One or both of them needs changing.

**Comment by rosebrallier** [comment]
Also, hoo boy the structure of this entire document needs help. Perhaps we could organize it by damamge types rather than by a mix of weapon types and damage types.

**Comment by Turtlelord26** [comment]
Of note, the "Melee Weapons" entry currently goes away with Melee 2.1.

**Comment by rosebrallier** [comment]
@bleehu signoff or objections?

**Comment by bleehu** [comment]
There is some slight difference in the way that we are treating damage types; Maybe we should call the ones that 1Source came up with in his weapon/armor system weapon types? Or just merge the two systems? I think we want to just merge the two systems.

**Comment by Turtlelord26** [comment]
Defining weapon types seems of dubious value anyway. If we redefine [Ballistic/Plasma/Laser] Weapon as "a weapon that deals [Ballistic/Plasma/Laser] damage", do all of the problems go away?

**Comment by rosebrallier** [comment]
As long as the solution [exterminates ](https://en.wiktionary.org/wiki/hill_to_die_on)any lists of damage types in which half of the items are labeled as weapons, I will be pleased.

**Comment by Turtlelord26** [comment]
Going to dredge this back up and ask again if we can dump weapon types and just have ballistic, plasma, and laser be damage types like the rest.

**Comment by bleehu** [comment]
Are we also dumping the relationship between shields/armor that ballistic/plasma/laser has?

**Comment by Turtlelord26** [comment]
I wasn't thinking that we would, why?
