### ISSUE TITLE
Feature Request: Higher-Level Shotgun Ammo: Flechette Rounds

### ISSUE THREAD

**Issue by Turtlelord26** [trowl223/Compound_X#496]
Physically similar to buckshot - a spreading payload of lots of small objects. The difference is that in this case the objects are nauseatingly sharp bits of pointy, flight-stabilized steel instead of round lead balls.

**Comment by bleehu** [comment]
Yes Please!!!!!

**Comment by bleehu** [comment]
Masterdiekillsu, could you give us some new shotgun ammo? Don't forget to branch off of the *dev* branch.
https://github.com/bleehu/Compound_X/blob/dev/Items/04_00_WeaponAttachments.txt#L604

And here's the link to the how-to stuff in case you get stuck
https://github.com/bleehu/CX_Design_Guide/tree/master/DevProcesses#how-we-make-pull-requestsadd-new-stuff
https://github.com/bleehu/CX_Design_Guide/blob/master/DevProcesses/welcome.md#7-design-bootcamp

**Comment by Masterdiekillsu** [comment]
Feature Added! Issue closed
