### ISSUE TITLE
Feat stacking not prevented

### ISSUE THREAD

**Issue by Wildlovelies** [trowl223/Compound_X#50]
Need to add verbage to state that you can only take feats once unless otherwise noted.

else we have someone with 5 cases of double tap...

**Comment by trowl223** [comment]
Agreed. No feat can be taken more than once unless specifically stated by the feat itself.

**Comment by bleehu** [comment]
Don't write that here! Put it in the rules! Or direct one of us to fix it!

**Comment by trowl223** [comment]
Approved merge, closing issue.
