### ISSUE TITLE
Gripe: Skill Points at Level One

### ISSUE THREAD

**Issue by Turtlelord26** [trowl223/Compound_X#517]
A strict reading of the relevant rules does not provide a clear answer to how many skill points a character has at level one.

Basic Rules: Secondary Stats: Skill Point Gain says only that you get skill points "every time you level up", while the Basic Rules: Leveling states level one skill points as 'given' + 'static'.

**Comment by rosebrallier** [comment]
If I change the text in Leveling from "Given Static 2xSkill Point Gain" to "Gain 2xSkill Point Gain per Level", will that clarify things?
The skill point column of Leveling is mean to be a single line of text.

**Comment by rosebrallier** [comment]
Ahhh. And I'll write an "Assigning Skills to a Character" section into Basic Rules to clarify that at Lvl1, a character should have 2xSPG skill points to spend in addition to any class passives and racial traits.

**Comment by rosebrallier** [comment]
@bleehu Is this plan in line with your understanding of the clarity problem?

**Comment by bleehu** [comment]
I also think we should leave room for backgrounds to confer skills,  but other than that, ya!

**Comment by 1sourcecontrol** [comment]
Humm. It doesn't say anywhere about "gain 5 skills at level 1 with 10 points each"? I woulda thunk we had that written down by C2.0.

But it sounds like the old system is gone anyways

**Comment by Turtlelord26** [comment]
Yes we deliberately killed the 5 skills at lv 1 thing to make room for backgrounds.

**Comment by bleehu** [comment]
But then we haven't finished backgrounds yet...

**Comment by rosebrallier** [comment]
I mean, we killed the lvl 1 5@10 rule for balance and aesthetic reasons too, right?
