### ISSUE TITLE
Mendar is more op than Kensington at gaining followers...

### ISSUE THREAD

**Issue by Wildlovelies** [trowl223/Compound_X#529]
Mendar's colorful! Ability has no duration and no save after initial... so If I woo a crowd, do they follow me forever?

**Comment by dfuchs2** [comment]
Looks that way. Maybe they should roll a will save every turn?

**Comment by Turtlelord26** [comment]
Every turn is a lot of dice. How about every few minutes, plus a explicit break on entering combat?

**Comment by bleehu** [comment]
Seems to me like it's an instant. So you'd have to roll every time you want to either calm or rile up a crowd you'd need to roll. But having a crowd riled or calmed is not the same as wooing a crowd into followers.

**Comment by bleehu** [comment]
https://github.com/bleehu/Compound_X/blob/dev/CharacterCreation/01_Species.txt#L292
for clarity

**Comment by Turtlelord26** [comment]
Ah, so it's intended to be more like a diplomacy check than a dominate person spell. That's how I thought at first but Wild's question seemed plausible...maybe we need a small quantity of guardrail text?

**Comment by bleehu** [comment]
I think so; it wasn't a wild leap for Wild to make. at the very least, we should say what happens specifically if a will save is failed.

**Comment by bleehu** [comment]
@dfuchs2 can you tackle this?
