### ISSUE TITLE
Create Third Drone Series

### ISSUE THREAD

**Issue by bleehu** [trowl223/Compound_X#553]
Before we ship the new reworked Drone series as part of @Reveraine's Species rework project, we need at least one, maybe two more Drone Series. Please make one! 

When working on the new races, please note that you'll need to branch off of Rev's *Races-Push* branch (which is temporarily serves as a superbranch for Drone work) and *NOT dev*.
https://github.com/bleehu/Compound_X/blob/Races-Push/CharacterCreation/01_02_Species_ECSC_Security_Drone.txt#L124 Again, you'll have to branch off of Races-Push making a feature branch and then making a PR when you're done with work to pull Races-Push<-your-feature-branch. 

Your new Drone Series should have 
[ ] a name
[ ] a size 
[ ] a description of how their appearance and anatomy are different

Favored Terrain is optional, and we'll track Available traits in a separate Issue. 

As an idea, a lighter weight Drone that is maybe more mobile and/or of smaller size might be a good idea of where to go with your new series.

**Comment by dfuchs2** [comment]
Is this now considered closed? Should we add any more drones, or should we keep to the three that we have?

**Comment by bleehu** [comment]
Yes, this is closed.

I recommend that we stop at 3 drones for now and focus on getting races-push to a shippable state.
