### ISSUE TITLE
Gripe: Need reaction check

### ISSUE THREAD

**Issue by dfuchs2** [trowl223/Compound_X#559]

**Comment by bleehu** [comment]
Or do we want characters that have reaction abilities to be able to react to more than 12 things per round?

**Comment by Turtlelord26** [comment]
I'm open to the possibilities of feats or abilities expanding character's abilities to react, but I want a baseline limit of 1/round.
If we start messing with that, remember that some of the most broken content I've seen out of DnD has involved attacks as Reaction-equivalent actions with high or unbounded limits on the number available.

**Comment by bleehu** [comment]
Can we expand that cap to three per round? Most other reactions also have another cost to them, or at least they should. I want pre-emptive strike to be the bane of the Antlion Hatchling rush, but not be broke-as-hell. I think that balance is closer to a 3 per round than 1 per round.

**Comment by Turtlelord26** [comment]
We can test that. Fair warning that this increases the likelihood that something in the future that looks ok breaks stuff. Would like a design note for that extra cost to Reactions.

**Comment by bleehu** [comment]
https://github.com/bleehu/CX_Design_Guide/issues/102
