### ISSUE TITLE
Gripe: Add fire extinguisher rules

### ISSUE THREAD

**Issue by dfuchs2** [trowl223/Compound_X#560]

**Comment by bleehu** [comment]
Expected as an item in the Items list.

**Comment by Eryneril** [comment]
Should it be in Misc Items or Tools?

**Comment by bleehu** [comment]
Consumable? Unless it's a space age extinguisher that you can refill?

**Comment by rosebrallier** [comment]
I love the idea of a rechargeable extinguisher! (which would put it under tools, with details on how to recharge). In related news, [this.](https://i.redd.it/ffczntn8u2jz.jpg)
