### ISSUE TITLE
Gripe: Mendar shouldn't be able to use Very Normal

### ISSUE THREAD

**Issue by dfuchs2** [trowl223/Compound_X#562]

**Comment by bleehu** [comment]
https://github.com/bleehu/Compound_X/blob/dev/CharacterCreation/03_Feats.txt#L644 'cause fish people that have glowing scales are hard to consider "normal"

**Comment by rosebrallier** [comment]
Wasn't there talk at some point of making Very Normal human-exclusive?

**Comment by Reveraine** [comment]
We have two options, currently Very Normal is in the works to be human-exclusive. However, with a few changes, and with backgrounds pending, we could have Very Normal be open to all species, but have the constraints be tied to backgrounds; for instance, a soldier could appear very normal to another soldier background, but someone with a dancer background would see through it. 
That, of course, gets complicated, so I'm more in favor of the first option, if only for the sake of GM's not having to come up with backgrounds for all their NPCs Ever.

**Comment by rosebrallier** [comment]
I'm in favor of either human-exclusive Very Normal, OR it only working on people of the same species.

**Comment by bleehu** [comment]
I like it for humans only.

**Comment by Turtlelord26** [comment]
Accomplished in the Species Rework project branch.
