### ISSUE TITLE
Gripe: R_C/Conditions has incorrect data

### ISSUE THREAD

**Issue by dfuchs2** [trowl223/Compound_X#563]
"Death and Dying" is no longer in the Basic Rules Document.

**Comment by bleehu** [comment]
https://github.com/bleehu/Compound_X/blob/dev/01_05_Conditions.txt#L18

We should fix this in dev and let the fix trickle down by our usual release process. The above should now say "in combat rules section"

@Eryneril, can you take this one? I'm trying to spread the gripes out pretty evenly among our devs.
