### ISSUE TITLE
Manual Tone Inconsistencies

### ISSUE THREAD

**Issue by Reveraine** [trowl223/Compound_X#567]
What do we want our tone to be? Right now, the rules vary from being very light-hearted and sometimes silly to serious and completely matter-of-fact. Before we can do a real, hardcore pass on the rules, we should decide how we want our manual to feel.

**Comment by bleehu** [comment]
Having talked with Rev about it, I'm coming down on the side of having a more matter-of-fact universal tone. The game is fun enough that trying to dress it up with too much humor detracts from it and slows down the work on the rules.

**Comment by Turtlelord26** [comment]
We can always add fluff in strategic sections if we deem it appropriate at the very end, during a dedicated language pass with an eye at published consumption.

I was always going to prefer formalism, because that's what I'm more comfortable making.

**Comment by rosebrallier** [comment]
Okay; I enjoy writing and reading in conversational tone, but I can live with formal. :(
We def did need to pin down our target tone though. Thanks for the issue Rev!

**Comment by bleehu** [comment]
Addressing in this PR https://github.com/bleehu/CX_Design_Guide/pull/99
