### ISSUE TITLE
Paladin nanite addition

### ISSUE THREAD

**Issue by Wildlovelies** [trowl223/Compound_X#57]
@trowl223  paladins were mentioned in our last play session not having bonus nanites that were intended.

**Comment by trowl223** [comment]
Bonus should be less than a spell caster's bonus, maybe +75 static, or +45 +5/level.

**Comment by bleehu** [comment]
Well don't write it here! Put it in the rules!!! Or if you're not going to make the change yourself, direct either myself, or @1sourcecontrol or even @Wildlovelies  to make the change.

**Comment by bleehu** [comment]
@Wildlovelies do you want to take a shot at making a branch -> making the fix -> making the pull request -> profiting? Or are you having more fun breaking things?

**Comment by Wildlovelies** [comment]
breaking

**Comment by bleehu** [comment]
lol, alright :) @trowl223 mind if I take it?

**Comment by trowl223** [comment]
Not at all.
