### ISSUE TITLE
Rules in item doc :(

### ISSUE THREAD

**Issue by rosebrallier** [trowl223/Compound_X#578]
https://github.com/bleehu/Compound_X/blob/1823535425f69e218f7652c7a1f7519659050988/Items/04_03_SMGs_%26_Shotguns.txt#L1-L8

**Comment by rosebrallier** [comment]
nvm it's in all the gun docs

**Comment by Turtlelord26** [comment]
It is still correct that that rules snippet should be integrated into the weapons section of Combat Rules and not left in the gun item documents.

**Comment by rosebrallier** [comment]
Fair enough :)
