### ISSUE TITLE
Fix Crosstrain

### ISSUE THREAD

**Issue by bleehu** [trowl223/Compound_X#59]
We pulled the cross train feat from both RC and play, but it's still in dev. Is it worth the man-hours to try to balance it? Even if we fix it this time, it's a design landmine that will come up every time we change class feats or add a new class. 
On the other hand, it provides flexibility to build characters that fit between the class niches that we have already released. Being able to cross train adds a lot of fun complexity to the character building puzzle.
We don't need to decide right now, but until we decide we'll need to keep pulling it out every time we merge dev to RC.

**Comment by 1sourcecontrol** [comment]
I think until the game reaches its final form, crosstrain should be limited to known interactions. In other words, only allowing certain class feats to be crosstrain'ed. 
Ideally, one of us would run that crosstrained feat through abuse checks with all other classes.

**Comment by trowl223** [comment]
Nope, throw it out. In my opinion, it necessitates balancing every class ability from the lens of every other class. More work than may be possible at this point, and more work than *I* would want to do, not sure about anyone else. Someone told me once that a certain WildLovlies was able to take base classes and make characters from many other games without using crosstrain. My intent for the class system as a whole is to allow any character concept to be translatable into a class. It seems to me that this is possible without Crosstrain.

**Comment by Wildlovelies** [comment]
I think we could easily limit, list cross train capabilities under each class, Hunter cross class options: Assassin, marksman, etc. I could easily come up with cross classes that make sense, and you could have others be like signature move feat, where players give a reason that the dm has to approve to cross class. Leaves the options for players there, but limits them to known interactions or  accepted ones.

**Comment by Wildlovelies** [comment]
ill do a quick list for thought:
Soldier: Doctor, Priest, Hunter, Pilot  (I see soldiers kind of like a jack of all trades but master of none)
Specialist: Soldier, Doctor, Berserker
Doctor: Priest, Pilot
Engineer: Priest, Pilot, Soldier
Priest: Doctor, Adept
Pilot: Priest, Doctor, Soldier, Adept
Adept: Priest, Doctor, Soldier, Hunter
Hunter: Doctor, Marksman, Assassin
Mage/Sorc: n/a class feat is their caster class
Gunslinger: Hunter, Assassin
Assassin: Hunter, Berserker, Monk
Marksman: Hunter, Doctor, Priest
Berserker: Soldier
Monk: Assassin, Berserker
Paladin: Soldier, Doctor, Priest

I use Doctor loosely, as a medpack with a little medicine skill can do something similar. In fact is so gimped I may start a thread.

**Comment by trowl223** [comment]
Thats a good list for a later time, but for now i think we should focus on fixing whats in front of us. We're going to have a lot of potential changes coming soon and the classes have enough depth to them as-is for a wide variety of character creation.
Verdict: Remove from Play, RC and Dev.
