### ISSUE TITLE
Gripe: Critical Rules

### ISSUE THREAD

**Issue by Turtlelord26** [trowl223/Compound_X#591]
No Critical success/failure rules in Basic Rules for skill checks.

Gun Jam (equivalent to attack roll critical failure) assumes constant jam range of two, but should reference the jam range stat on individual weapons.

Accuracy critical rules only probably apply to melee strikes, not explicit.
No critical rules for Guard (if we don't want any, we need to say so), no critical failure rules for melee accuracy (given melee weapons can't jam).

**Comment by rosebrallier** [comment]
Shwoops. I'll copy the crit rules for skills over

**Comment by rosebrallier** [comment]
Skill check Criticals are written, in-combat rules still need help.

**Comment by Turtlelord26** [comment]
A thought: instead of setting a crit-fail for melee weapons that always misses, give Guard a crit-success that always wins. Mathematically it's identical, but should feel better and solve the third subgripe clump (minus edge case of both rolls critting, which needs to be handled).
