### ISSUE TITLE
Gripe: Shock DC to save vs 70+ dmg

### ISSUE THREAD

**Issue by rosebrallier** [trowl223/Compound_X#596]
Is exorbitantly high. Decreasing the DC may also help buff enemies.

**Comment by bleehu** [comment]
This line here https://github.com/bleehu/Compound_X/blob/play/01_02_Combat_Rules.txt#L214 
Should we remove that exception entirely and simplify that rule out? @Turtlelord26 ?

**Comment by Turtlelord26** [comment]
Are you asking whether we should remove the rule entirely? (It's a standalone rule, not an exception to another rule)
If so, I think I do agree that damage-induced Shock saves are an unnecessary rules complication and that CX would not be meaningfully diminished by their loss.
