### ISSUE TITLE
Gripe: Flamethrower Aoe

### ISSUE THREAD

**Issue by rosebrallier** [trowl223/Compound_X#599]
Flamethrowers should have an Aoe option.

**Comment by bleehu** [comment]
@dfuchs2 Do you think you can take this one? Or are you swamped?

**Comment by Turtlelord26** [comment]
I rather like the lv 1 flamethrower as a single-target weapon that shoots smaller globs of fast-burn-up gel into faces. That said, we're also missing a higher-level flamethrower. Can we solve two problems at once here?

**Comment by dfuchs2** [comment]
Doesn't look like anybody has taken this one yet. I'll do it next sprint. I very much like the idea of a higher-level flamethrower that acts differently than the one we already have.
