### ISSUE TITLE
Medic damage ramp too steep

### ISSUE THREAD

**Issue by bleehu** [trowl223/Compound_X#60]
We need to balance the ramp-up of medic power a little with new feats. I intend to do this by lowering the number of nanites generated by Hippocratic powers.

**Comment by Wildlovelies** [comment]
The power band as far as nanites go, Honestly I think **exempting** medic/engineer from nanite regen would help fix them more so than nerfing their nanite gains from spells. although I cannot account for medic dmg from spells, as the only damaging spell I used was nanite spike.
