### ISSUE TITLE
Lower rate at which medic gets malpractice powers

### ISSUE THREAD

**Issue by bleehu** [trowl223/Compound_X#61]
Medics are getting to offensively powerful too soon. Instead of getting a malpractice spell every level, get one every other level and flatten the tree a little bit.

**Comment by Wildlovelies** [comment]
playing one felt the opposite, I couldn't do enough offensively by lvl 5, all I could really get  was moderate hallucogen, granted I have not really crammed numbers on them. But I think they are far stronger as a controller with hallucinogens. which moderate hallucinogens with nanite spike is 80 nanites, which is two heals, for one attack. A better look might be at duration and save dcs vs hallucinogens as they are very high.

**Comment by bleehu** [comment]
I think this comes down to a disagreement over what "enough offensively" means. With the crit build, Medics are becoming a viable solo class. Which you like to play, but are somewhat less interested in playing with. We can discuss specific evidence of that offline if you'd like. 
Solo classes are a design that I would like to avoid entirely in CX. We would like crit builds to still be fun and powerful, but not solo. So lengthening the ramp-up is the solution that Taylor and I have decided on. 
We are keeping the DCs very high to create the strategic dynamic where you are very likely to get a payoff as a medic for using a spell which costs a lot of nanites, but the effects can still be shrugged off by enemies which have a very high save against that particular type of effect. Such an enemy would telegraph that resistance in their description. This way it is easy to be killed by bad strategy, and hard to be killed by uncooperative dice.
