### ISSUE TITLE
Update Nanite Class feats 

### ISSUE THREAD

**Issue by bleehu** [trowl223/Compound_X#610]
There are several classes that use old-school nanites. We need to update them to our new nanite standards.

**Comment by bleehu** [comment]
working on handling in PR #687 PR #683 PR #684 PR #685 PR #688 PR #689 et. al. The work was broken up by class to prevent a problem with one feat from keeping all of them from being updated.

**Comment by Turtlelord26** [comment]
@Bleehu are there any class feats left to modify or can we declare victory?

**Comment by bleehu** [comment]
Victory is mine!
