### ISSUE TITLE
Nanite Removal Issue Tracking: Active Feats

### ISSUE THREAD

**Issue by Turtlelord26** [trowl223/Compound_X#620]
Working on the Turtlelord26-Nanite_Removal_Project-Superbranch

Active feats need a dedicated rule paragraph to describe how to use Medical Nanites to pay for them.

**Comment by bleehu** [comment]
This new rule should be in the feats document, right?

**Comment by Turtlelord26** [comment]
Much like with the items documents, I would prefer feats to remain a pure list and leave the rules in the dedicated rules documents, in this case Basic Rules.
