### ISSUE TITLE
Double-Tap needs editing

### ISSUE THREAD

**Issue by trowl223** [trowl223/Compound_X#63]
Currently too powerful with the combined crit expansion and damage expansion.
Suggested change: since the feat is literally expending another bullet, I think that the feat should only affect rolls that fall into Extra Crit range (96-100 normally), and they should do double damage. I also think that this feat is linked to a problem with the crit system in general, which may need to be visited here or in another issue thread.

**Comment by bleehu** [comment]
Do you want @1sourcecontrol to write up a proposal for a fix?

**Comment by Wildlovelies** [comment]
Splitting it into two feats could be an easy fix

**Comment by trowl223** [comment]
@1sourcecontrol, @Wildlovelies and I spoke about this in our play session a week ago and yes, we may make double tap similar to what I mentioned, remove the crit range expansion, and add a new feat which enhances the crit range.

**Comment by 1sourcecontrol** [comment]
I added two branches + pull requests, please see them for more discussion on the details. Close?

**Comment by bleehu** [comment]
Close it when we merge Pull #74
