### ISSUE TITLE
Neglected Rule: Criticals & Autofire

### ISSUE THREAD

**Issue by Turtlelord26** [trowl223/Compound_X#631]
https://github.com/bleehu/Compound_X/blob/R_C/01_02_Combat_Rules.txt#L465

> You cannot score Critical Hits while firing a gun in burst or automatic mode.

We have not been paying any attention to this item at all. So, do we want to keep it? Does it serve an important balance function, or is it enough more fun to have many crits that we want to kill it?

**Comment by bleehu** [comment]
I think we keep it. It's simple enough to remember, and it keeps a clamp on damage explosions

**Comment by Reveraine** [comment]
We're going to have to get better at remembering it, then =P

**Comment by bleehu** [comment]
Can I close this as Won't-Do?
