### ISSUE TITLE
Nanite Removal: Engineer Energy vs Equipment Energy

### ISSUE THREAD

**Issue by Turtlelord26** [trowl223/Compound_X#635]
Working on the Nanite Removal Superbranch

These two resources need to not be able to interact, which means one of them is getting renamed and possibly reflavored.

**Comment by rosebrallier** [comment]
Could we use Battery Power/Charge?

**Comment by Turtlelord26** [comment]
Too much the same thing. I want it to be distinct enough that no one's asking awkward questions about why they can't jury-rig one to the other.

**Comment by rosebrallier** [comment]
Something something different current output something something required amperage something something?

**Comment by Turtlelord26** [comment]
Level 10 Engineer with 60 points in Jury-rig rolls up and says "I have a transformer for that!"

I have a couple ideas. I didn't really like Energy in the Engineer anyway since it didn't feel right for a feedback resource like the Doc's adrenaline.
One of the ideas is in fact a straight replacement with Adrenaline.

**Comment by rosebrallier** [comment]
How would we explain using a hormone for building things? Like it makes sense for medical stuff, but engineering?

**Comment by Turtlelord26** [comment]
Closing out as complete assuming eventual merge of the Nanite Removal Superbranch.
