### ISSUE TITLE
Doctor Class feat too weak

### ISSUE THREAD

**Issue by Wildlovelies** [trowl223/Compound_X#64]
Essentially we are doing the same thing with a med pack, too weak in my opinion,

**Comment by bleehu** [comment]
I agree. I'll write up a change then submit to Trowl. (not tagging yet, 'cause I've already been pretty noisy).

**Comment by trowl223** [comment]
Maybe we should remove them entirely and the Doctor class can rely on its procedures, similar to the Warlock / Sorcerer classes?

**Comment by bleehu** [comment]
That seems almost too easy. Maybe a bit lazy. It should be good for something.
