### ISSUE TITLE
Proposed Idea on monks

### ISSUE THREAD

**Issue by Wildlovelies** [trowl223/Compound_X#65]
@trowl223 
I believe you and I have the only monks in existence, as their limitations make them a much more difficult class to play, I believe they are very end game characters and would love to take mine there. I have an idea, their kit as of right now is so limited the general player will not go near them. I know you have stated that you do not like classes that give stats, but I propose that Monks get bonus stats as part of what makes them unique,  5 extra skill points per lvl (or 2.5 * int per level) for example, or bonus to all stats +1, but you give up your race stat bonus' you would still keep malices though. As a monk you give up your old self to follow the way, the way is an enhanced life, and should be treated that way. stacking bonus' to help level the playing field a bit more against your item using enemies.

**Comment by trowl223** [comment]
Interesting ideas. I still don't like the idea of classes granting stat bonuses or other such enhancements beyond specific skills inherent to the class (Hacking for the Priest, Sniping for the Marksman, etc.). I'll look into the Monk class pertaining to playability, but certain classes are going to have a steep learning curve. I will not buff a class for the sake of making it more appealing to the user base. We have discussed the monk in the past and that even though at level 10 and above it is a very strong class, it does have some issue potentially reaching level 10 alive.
