### ISSUE TITLE
OP Build1: Berserker

### ISSUE THREAD

**Issue by Wildlovelies** [trowl223/Compound_X#66]
-Berserker: lvl 3 13 str, full armor plus 10 dr from passives, only thing they spend money on is their weapon and armor at this point so they can afford the first additional cyborg upgrade price of $2000. add power fist, you are doing 143 dmg per hit, you have 50 dr 100% coverage, and at lvl 5 any dmg you do take just increases your melee dmg even more. Add dual wield or akimbo...

**Comment by bleehu** [comment]
I'll write up a fix and then submit it to @trowl223 for approval.

**Comment by trowl223** [comment]
As mentioned before, we're going to be limiting Lvl 1 to 10 in any stat (including with a cyborg upgrade) and removing the class-based buff.

**Comment by 1sourcecontrol** [comment]
@trowl223 To make it more plain for me, does that mean a cyborg with 10 PER doesn't gain another stat point by getting an additional vision enhancement @ lvl 1?

**Comment by bleehu** [comment]
Removing which class-based buff?

**Comment by trowl223** [comment]
@1sourcecontrol Yes. If you want to have the other benefits of a cyborg enhancement, the player should spec their stats so they have room for the increase due to enhancement.
@bleehu the Berserker strength buff and intelligence debuff.

**Comment by bleehu** [comment]
removed in commit 7854f6a00beecb10a1b6afc1d7c7bd7ebb1bf6c5
Should have made a branch. Whoops.

**Comment by 1sourcecontrol** [comment]
I don't know what our opinion is on "necro'ing" threads, but I'm talking on this issue since we already have the relevant discussion:

@trowl223 
So then, once I'm level 2 or level 4 or just _not_ level 1, I can purchase an enhancement for a 10 point primary stat (or when I get an additional stat point as part of leveling up), I can push it to 11 points? And the max I can ever have is 15 points in a primary stat, correct?

Also, is it stated anywhere in the rules about this level 1 cap?

**Comment by bleehu** [comment]
Issue #47 is directed at stating that exactly. 

what is necro'ing threads?

**Comment by 1sourcecontrol** [comment]
Woops, thanks.

necroing is reviving dead (typically really old) threads

**Comment by bleehu** [comment]
I think we revive threads as long as they're relevant. :)
It's also my opinion that a limit on only level 1 character stats doesn't make much sense, since players typically level up past level 1 pretty quickly.

**Comment by trowl223** [comment]
@1sourcecontrol Correct, its just a character creation cap so that all characters start off on similar footing, no one should have higher than a +20 modifier @ Lvl 1

**Comment by bleehu** [comment]
That doesn't fix the problem! It just delays the problem until level 2? We need to solve the problem for all levels. 
Could we set hard caps for every level that increase at certain increments?
i.e.
levels 1-3 cap 13
levels 4-6 cap 14
levels 7-9 cap 15
levels 10-12 cap 16
levels 13-15 cap 17
levels 16-18 cap 18
levels 19+ no cap - if you've played this far, you've earned the power trip.

**Comment by trowl223** [comment]
It does though, no player can have higher than 10 points at level 1, so all players who max out a stat will have 10 as their absolute highest starting point. That as i perceive it is the crux of this issue.

The first stat increase isn't until level 5, so all players will have a max of 10 until level 5, unless they are a cyborg and pay for an augment at level 3 for $2000. They can pay for another augment at level 8, so assuming they spend $4000, they can have a 13 stat at level 8.

**Comment by bleehu** [comment]
oh! So you felt that it was implied that at level 2 you didn't get reimbursed for the stat point you we being capped against. I think that would work.

**Comment by trowl223** [comment]
Yes, precisely.

**Comment by 1sourcecontrol** [comment]
I made a reply to this topic in: #113. Why don't we close this issue here, and continue over there?

**Comment by trowl223** [comment]
Agreed.
