### ISSUE TITLE
OP Build2: Marksman

### ISSUE THREAD

**Issue by Wildlovelies** [trowl223/Compound_X#67]
-Marksman: both builds can be broken, tech rounds with machine gun pistols and nanite regen..
Multi pin at lvl 10 is scary as hell, pick up to 13+ targets, everytime they do anything you get to shoot them

**Comment by trowl223** [comment]
As mentioned in Issue #58, a potential solution is to allow the marksman feats only be usable with long rifles.
For multi-pin we can limit the number of targets to fire at per turn, but maintain that each pinned target /can/ be fired at, it would be user discretion on which targets are a primary threat rather than just firing at everything that twitches.

**Comment by Wildlovelies** [comment]
also we need to limit direction, makes no sense to pin someone and shoot freely at them if they are behind you.

**Comment by trowl223** [comment]
You say "makes no sense". I say its a class ability which enables them to track any targets they have recently hit. Think about the Medic's heartbeat sensor, is that much different? I do think we should limit how far back "recent" is, I'll come up with a solid edit for the feat that addresses the following issues:
- Too many targets are able to be feasably fired at with a bolt-action rifle
- Limit how long a target is considered "watched"

Any other concerns?

**Comment by Wildlovelies** [comment]
No

**Comment by bleehu** [comment]
Heartbeat simply tells you if an enemy is there, it doesn't grant any reactions to their movement. I agree that 'recent' could be more specific than it is, but the way that it's written that would be at DM discretion. And it probably should only apply to long rifles. Seems like an easy fix. @trowl223 do you still want to handle this personally, or do you want to delegate it?

**Comment by trowl223** [comment]
Since @1sourcecontrol is doing the combat update stuff, I'm going to reassign to him. My computer is still buggered and I need to find time to fix the setup so I can resume direct dev work.

**Comment by bleehu** [comment]
fix merged. Closing issue.
