### ISSUE TITLE
gripe: add note  in armor

### ISSUE THREAD

**Issue by bleehu** [trowl223/Compound_X#674]
In the armor section of combat rules, make a note that most arrmor stops electrical damage.

**Comment by Turtlelord26** [comment]
Obsolete now that Electrical damage bypasses armor (and hits shields)?

**Comment by bleehu** [comment]
Yup, hits shields first. https://github.com/bleehu/Compound_X/blob/R_C/01_04_Damage_Types_and_Armor_Types.txt#L64
