### ISSUE TITLE
OP Build3: Soldier

### ISSUE THREAD

**Issue by Wildlovelies** [trowl223/Compound_X#68]
-it'll heal soldier plus full armor: up to 50dr 100% coverage, plus only taking half dmg for everything else...

**Comment by trowl223** [comment]
As discussed, soldier can have a third look taken at it. I'm not comfortable with them and they could use something a little different. Yank for now? I feel that the current difference in builds between Specialist and Soldier is pretty small, so we can direct front-line damage dealers to build as a Specialist in the time being.

**Comment by bleehu** [comment]
Sounds like the fix here is to just take a look at the "It'll heal" feat. Soldier and Specialist are already pretty different; take a look at the way Zach's specialist, Alex's specialist and Gnat's specialist play versus how Derek and Kevin's soldiers play. Maybe we can do some minor tweaking to increase the difference between them, but I think yanking them is way overkill.

**Comment by trowl223** [comment]
Alright.
Verdict: Fix It'll Heal. My recommendation is to allow the full amount of "ignored" damage to be taken at the end of the conflict, instead of half or 1/3. This damage does not have DR applied to it, so if a solider lets 4 or 5 shots "heal" during the course of an encounter, they will likely die at the end of the encounter. We can add some restrictions so that these wounds cannot be healed by normal means or require higher DCs to restore the Soldier to full spec.

**Comment by bleehu** [comment]
Sounds good. Who do you want to write it?

**Comment by 1sourcecontrol** [comment]
Am I reading this right? So the soldier takes 1/2 damage until the end of conflict, then basically, instantly dies by taking another full set of damage?

**Comment by bleehu** [comment]
@1sourcecontrol That's correct. Maybe we could do better?

**Comment by trowl223** [comment]
Its the whole adrenaline rush thing on a new level. The soldier gets so amped on trying to finish the conflict that they can ignore crazy amounts of pain and damage to accomplish their goal. Once the adrenaline wears off (after encounter is over) they succumb to the blood loss / system failures. If you guys don't like this mechanic we can look at something else or another way of doing it, I'm not super attached to it.

**Comment by bleehu** [comment]
This has been sitting too long, I'm going to assign myself and take care of it.

**Comment by bleehu** [comment]
Taken care of
