### ISSUE TITLE
OP Build5: Adept

### ISSUE THREAD

**Issue by Wildlovelies** [trowl223/Compound_X#70]
-Adept tank build, as it stands, adept can reach 60dr plus nanite shielding lvl 2

 also nanite regen crit build plus nanite shielding (nanite shielding listed as a separate nanite pool, nanite regen does not state which pool is filled) = near infinite effective hp

**Comment by trowl223** [comment]
As discussed previously, **Nanite regen does _not_ affect CS or Nanite shielding. They have a separate pool.** I realize that this is not mentioned in the rules, that should be the first change made.

Rule addition, regarding shields of all types:
"Shields run on a closed system which operates independent of the user's main Nanite pool. As such, regeneration of these shields occurs separately from any Nanite regeneration abilities, Nanite Packs, Medic abilities, or Spells."

Secondly, as disussed in Issue #46 Adepts will be removed until fixed.
