### ISSUE TITLE
Pistol Attachment limiting not listed

### ISSUE THREAD

**Issue by Wildlovelies** [trowl223/Compound_X#72]
Nit picky, but I cannot find where it says you can only put x attachments on pistol, or the opposite, cannot attach x to pistol

**Comment by trowl223** [comment]
Will address in attachments document or weapons document.
Pistols may make use of the following attachments:
- Sights with the "Pistol" keyword
- Aiming assistances like Lasers and Flashlights
- Barrel Attachments
- Slings with the "Pistol" keyword
- Ammunition
- Total Conversions with the "Pistol" or "Revolver" keyword, as applicable

Any other concerns?

**Comment by Wildlovelies** [comment]
nope, just they weren't listed. remembered this from doctor build

**Comment by trowl223** [comment]
I've added a response on the merge request thread, I'm going to close this issue since a solution is being worked on.
