### ISSUE TITLE
Salty Spacedog feat needs an update

### ISSUE THREAD

**Issue by bleehu** [trowl223/Compound_X#723]
The Salty Spaces of feat uses the old % notation for skill buffs. We should either update it to give a balanced bonus in the correct terms,  or yank it and replace it with @rosebrallier's new and awesome background system.

**Comment by rosebrallier** [comment]
Imo, the feat is different enough in function from Iron Stomach that I'd prefer to just edit it.

**Comment by rosebrallier** [comment]
See PR #749

**Comment by bleehu** [comment]
:shipit: Shipit Squirrel!

**Comment by rosebrallier** [comment]
Complete re PR #749
