### ISSUE TITLE
Alchemist in play under class.txt

### ISSUE THREAD

**Issue by Wildlovelies** [trowl223/Compound_X#73]
"Alchemist"

Mech summoner / P otions master

Passives: Repair/Tinker - 10 or ; +50 nanites.

Weapon Profs: Pistols, SMGs, Shotguns, Carbines.

Armour Profs: Recon, Light, Medium.

**Comment by trowl223** [comment]
needs to be yanked from Play and RC, class not yet ready for test.

**Comment by bleehu** [comment]
Whoops! I forgot to branch. But it's yanked from play. About to do RC.

**Comment by bleehu** [comment]
It's not in RC
