### ISSUE TITLE
Gripe: Thermal damage missing

### ISSUE THREAD

**Issue by rosebrallier** [trowl223/Compound_X#758]
I thought we agreed to roll Cold and Fire damage into Thermal damage, but there is no Thermal (or Cold) damage in [Damage and Armor Types](https://github.com/bleehu/Compound_X/blob/dev/01_04_Damage_Types_and_Armor_Types.txt), only Fire damage. When did this happen? Was it on purpose?
Blocking editing work on Human Species.

**Comment by bleehu** [comment]
I think I got called out. I failed to make the change in this PR. https://github.com/bleehu/Compound_X/pull/358/files 

That would mean that our frost-resistant Western Earthlings would be resistant to fire as well as frost, but I think that actually holds more accurately to how physics works. 
https://github.com/bleehu/Compound_X/blob/Races-Push/CharacterCreation/01_01_Species_Human.txt#L171

**Comment by bleehu** [comment]
I'll tackle this as part of gripe processing in sprint-after-next.
