### ISSUE TITLE
Changing critical hits with automatic weapons

### ISSUE THREAD

**Issue by 1sourcecontrol** [trowl223/Compound_X#77]
With regards to balancing issues #74 & #75; I propose that criticals should only be allowed to occur on weapons firing single fire (1 bullet per half action). 

1. Automatic weapons will still be very powerful since, I believe, they have the greatest potential damage output.
2. Combat turns will be sped up a little bit--less calculations/thought.
3. Potentially solution for a lot of abuse interactions that we've seen lately, criticals on 4 or 8 bullets per turn (4 firing actions, one or two weapons) instead of 24-48 bullets per turn. Reduces the milkability of nanite regen, and
4. From a realism perspective, I think double tap only makes sense for single fire weapons, "double tap an automatic weapon while firing automatically"? When a weapon is firing in automatic, I believe, by default, that weapon is firing as fast as it can. Fixes double-tap from being abused with automatic weapons.
5. Doesn't directly nerf crits but manages problem interactions with other abilities. 
6. Crit chance doesn't necessarily have to get nerfed into the ground.

What do you think?

**Comment by bleehu** [comment]
I really like this balance. It reminds me of the destinction that Halo:Reach made between precision weapons like the DMR and full auto weapons like the Assault Rifle. That led to really balanced weapon variety. It's simple, easy for players to understand. 
@trowl223 what do you think?

**Comment by trowl223** [comment]
Agree, approved.

**Comment by bleehu** [comment]
Great work guys! If the branch is merged, go ahead and delete it so we don't have a massive backlog of dormant branches and close out the issue if it's solved :)
