### ISSUE TITLE
Review of the words, Half-Action & Full-Action

### ISSUE THREAD

**Issue by 1sourcecontrol** [trowl223/Compound_X#78]
I know there has been some discussion on this topic so I'd like to push it along. :)
 
I think it would benefit the learning curve, ease-of-speaking, and ease of writing to change the half-action + full-action system to just "Action". For example, "I'm using my first action to move, my next action to aim, and my last two actions to fire" aka, 4 actions per turn.

I'm simply proposing a change to the words used.
It wouldn't take more than a couple hours to comb through the text files to make the change in dev.

**Comment by bleehu** [comment]
I think this is a good idea. Having four half actions per turn seems a little cloogy. What do you think, @trowl223 ? Should we assign @1sourcecontrol to make a branch and update this?

**Comment by trowl223** [comment]
Yes, but I'd like them to be referred to as "Action Points", which are a new stat for the player sheet. If we move to having all Auto weapons miss chances based on strength ( @1sourcecontrol  ) I'd like to have Action Points increase based on Dex. Maybe +1 per 4 points above 5, -1 per 4 points below 5. We'll decide balancing later, but its an idea I've been playing with.

**Comment by 1sourcecontrol** [comment]
Action points are more of a vague concept​; I went for as simple a term as I could manage.

But SMGs have auto miss chance reduced by DEX, as previously discussed. And I'm planning to open a future pull request for a feat that lets DEX be used in place of STR for the auto miss chance.

I'm concerned that, having DEX be used to control turn length will make DEX far too powerful.

**Comment by bleehu** [comment]
Marrying AP to Dex without reworking the whole stat system is gonna explode. Wildlovelies would choke us with DEX builds. 
Action Points remind me heavily of Fallout and Warhammer. It's a workable verbage, but I'm not crazy about it. DnD 4 used Standard Actions and Minor Actions, 5e uses Attack Action, Move Action and Bonus Actions. In both cases, Action Points could be spent to get more actions on a given turn than normal. I say this not to suggest that we steal those systems, just as a reference for the naming convention. To avoid being compared to other games, we could use the term 'Motions'. If we do go with Action Points, I'd like to make the disclaimer that it doesn't work like DnD in the rules.

**Comment by 1sourcecontrol** [comment]
This issue has been sitting around for almost a month, and I believe we've all had time to think about it. What's the plan? @bleehu

**Comment by bleehu** [comment]
Let's go with the term "Actions" and have them be atomic units. No more of this "half action" stuff.

Do you mind taking it? @1sourcecontrol ?

**Comment by trowl223** [comment]
Agreed.
