### ISSUE TITLE
Write the description of Sea Devil

### ISSUE THREAD

**Issue by bleehu** [trowl223/Compound_X#780]
https://github.com/bleehu/Compound_X/blob/SS/Races/Opaleites/CharacterCreation/01_04_Species_Opaleites.txt#L154

The appearance section of the Sea Devil Opalite sub-species is blank. We should fill that in.

**Comment by Turtlelord26** [comment]
@bleehu this appears to have happened.

> Appearance:
    Similar in size to the Mendars, Sea Devils, or Samek in the Opaleite tongue, 
are named for their inherenet ability to bioluminesce.
