### ISSUE TITLE
Write description for Deep Glow

### ISSUE THREAD

**Issue by bleehu** [trowl223/Compound_X#781]
The Opalite Sub-Species Sea Devil has a Species Trait "Deep Glow" that needs some prose before we're ready to release the new Opalites.

https://github.com/bleehu/Compound_X/blob/SS/Races/Opaleites/CharacterCreation/01_04_Species_Opaleites.txt#L162

**Comment by Turtlelord26** [comment]
@bleehu this is accomplished.
