### ISSUE TITLE
Paladin Spells: Crimson/Violet/Blue flame

### ISSUE THREAD

**Issue by bleehu** [trowl223/Compound_X#8]
What is the range? Blast Radius? How long does the burn last?

**Comment by trowl223** [comment]
This is an augmentation spell, which should be specified. It adds 20/40/60 damage to a single attack. Range depends on the weapon, blast doesn't exist because its a single target. Burn damage is dependent on the burn damage rules.

**Comment by bleehu** [comment]
don't tell me; write it in the doc!

**Comment by trowl223** [comment]
Current Phrasing, added "You imbue an ally's or your own weapon with divine energy.":
		{5} Crimson Flame: [25]
		|   You imbue an ally's or your own weapon with divine energy. +20 
		|	damage, single attack. Inflicts 1 Burn damage token.
		|
		V
		{10} Violet Flame: [45]
		|   +40 damage, single attack. Inflicts 1 Burn Damage token.
		|
		V
		{15} Blue Flame: [65]
		    +60 damage, single attack. Inflicts 1 Burn Damage token.
