### ISSUE TITLE
Gripe: Improvised Thrown Weapons

### ISSUE THREAD

**Issue by Reveraine** [trowl223/Compound_X#810]
Improvised thrown weapons needs guard rules. 
The possible distance for Improvised thrown weapons needs to be reevaluated.

**Comment by rosebrallier** [comment]
So, a strict reading of the [thrown weapons rules](https://github.com/bleehu/Compound_X/blob/f1201dd0744a03568d550640ef6aa60bf5f27885/01_02_Combat_Rules.txt#L392) indicates that Improvised Thrown Weapons should have Miss Chances equal to a miscellaneous Thrown Weapon of the same size, [-2 Accuracy.](https://github.com/bleehu/Compound_X/blob/f1201dd0744a03568d550640ef6aa60bf5f27885/01_02_Combat_Rules.txt#L237)
So, they don't need Guard rules, but they do need entries in [Melee and Thrown Weapons](https://github.com/bleehu/Compound_X/blob/dev/Items/04_01_Melee_%26_Thrown_Weapons.txt ) (one per weapon size).
