### ISSUE TITLE
Lvl 1 2h 6 ft spear range. (Melee)

### ISSUE THREAD

**Issue by Wildlovelies** [trowl223/Compound_X#834]
Realistically this weapon should have a range of 2m. Being that it is 2m long plus arm reach, on a weapon designed for thrusting

**Comment by Turtlelord26** [comment]
Leverage is a killer if you aren't holding it by the center. That said, 1m + arm is still much more than a sword, so I agree that it would be nice to somehow represent that mechanically.

Is it reasonable or insane to keep it to 1m range but let it threaten opportunity attacks at 2m?

**Comment by bleehu** [comment]
That seems reasonable to me. @Wildlovelies ?

**Comment by Wildlovelies** [comment]
To be fair, this a 2m long thrusting weapon, even holding it in the center, that is 3 feet on the end of a characters arm length which most average between 2 ft and 3 ft long arms. I understand for balance issues if you want to do it that way, this is just my 2 cents. If it was a halberd where slicing is part if its expected attacks then I would be more inclined. But specifically a hunting spear that sticks into people is going to have a barbed tip that doesnt do well with that kind of attack

**Comment by Turtlelord26** [comment]
I hesitate to introduce facings to our system because I think they come with lots of mechanical baggage, but if we could find a way to do it gracefully I wouldn't be opposed to giving the spear 2m range but only in front of the user.

**Comment by Wildlovelies** [comment]
1m range, +1m range on the player's turn?

**Comment by Turtlelord26** [comment]
I like that. What would you say about combining it with "costs 1 Action to switch targets if the second target is at least 2m away from the first"?
