### ISSUE TITLE
Classes with stat bonus'

### ISSUE THREAD

**Issue by Wildlovelies** [trowl223/Compound_X#84]
In an interest to make Taylor's life easier I have found all of the classes with stat modifications:
Assassin: +1 dex, -1 luck
Berserker +1 Str, +1 fort, -1 luck
Monk: +1 dex

**Comment by bleehu** [comment]
Should we remove these?
If this is helpful, that's awesome. As a rule of thumb moving forward, I'd like to keep Issues limited to actionable work or concerns that need attention.

**Comment by Wildlovelies** [comment]
it is actionable, @trowl223 said he wanted to remove these stat bonus'

**Comment by bleehu** [comment]
removed in commit 7854f6a00beecb10a1b6afc1d7c7bd7ebb1bf6c5
Should have made a branch. Whoops.
