### ISSUE TITLE
Write Military Background Perks

### ISSUE THREAD

**Issue by rosebrallier** [trowl223/Compound_X#847]
Requires description for Veteran

**Comment by rosebrallier** [comment]
PR into [rosebrallier-backgrounds](https://github.com/bleehu/Compound_X/tree/rosebrallier-backgrounds) --> CharacterCreation --> [04_Backgrounds](https://github.com/bleehu/Compound_X/blob/rosebrallier-backgrounds/CharacterCreation/04_Backgrounds.txt)

**Comment by bleehu** [comment]
I'll take this one, unless you've already got something written for it!

**Comment by bleehu** [comment]
done!
