### ISSUE TITLE
SPACE Origin Perk

### ISSUE THREAD

**Issue by rosebrallier** [trowl223/Compound_X#848]
Flavor text for Space Station origin

**Comment by bleehu** [comment]
What branch and what file do we add this in?

**Comment by rosebrallier** [comment]
PR into [rosebrallier-backgrounds](https://github.com/bleehu/Compound_X/tree/rosebrallier-backgrounds) --> CharacterCreation --> [04_Backgrounds](https://github.com/bleehu/Compound_X/blob/rosebrallier-backgrounds/CharacterCreation/04_Backgrounds.txt)
