### ISSUE TITLE
Trioch Origin Perks

### ISSUE THREAD

**Issue by rosebrallier** [trowl223/Compound_X#849]
Flavor text for Trioch system and Opaleite Colony world origins

**Comment by rosebrallier** [comment]
PR into [rosebrallier-backgrounds](https://github.com/bleehu/Compound_X/tree/rosebrallier-backgrounds) --> CharacterCreation --> [04_Backgrounds](https://github.com/bleehu/Compound_X/blob/rosebrallier-backgrounds/CharacterCreation/04_Backgrounds.txt)

**Comment by bleehu** [comment]
I think this was handled here https://github.com/bleehu/Compound_X/pull/916

**Comment by rosebrallier** [comment]
Yay!
