### ISSUE TITLE
Terran Origin Perks

### ISSUE THREAD

**Issue by rosebrallier** [trowl223/Compound_X#850]
Flavor text for Kepler System and Terran Colony origins

**Comment by rosebrallier** [comment]
PR into [rosebrallier-backgrounds](https://github.com/bleehu/Compound_X/tree/rosebrallier-backgrounds) --> CharacterCreation --> [04_Backgrounds](https://github.com/bleehu/Compound_X/blob/rosebrallier-backgrounds/CharacterCreation/04_Backgrounds.txt)

**Comment by bleehu** [comment]
@rosebrallier, it looks like these are already done? You have stats for:
| Colony World- Terran   | Gain Languages- Terran Common (+ 1 dialect), 1 Common or Trade Language of   |
|                        | choice. Gain 0.5 set of Nanites.      ?
