### ISSUE TITLE
Stun condition; what does it do?

### ISSUE THREAD

**Issue by 1sourcecontrol** [trowl223/Compound_X#89]
I saw it [here](https://github.com/trowl223/Compound_X/blob/db8ba27ec74ebd28220c3977baa101532aeb25c1/play/PlayerRules/CharacterCreation/04_03_Advanced%20Weapons.txt#L364-L365):
>Target rolls a fort save against electric damage, dc of 80%. On fail, target 
>takes additional 10 Shock damage per barb and is stunned for 2 turns.

What does "Stun" do? And should it be added to the conditions list in the basic rules?

**Comment by trowl223** [comment]
They can take no actions. Maybe the wording should be changed to paralyzed since its an electric shock inducing the stun.

**Comment by 1sourcecontrol** [comment]
You could call it "stunned/paralyzed" under basic rules then you can use either? Unless there is a stun effect that is different than paralyzed

**Comment by trowl223** [comment]
Yeah, that sounds good. They have the same effect, they are just used in different contexts
