### ISSUE TITLE
Paladin Spells: Prayer of Silence

### ISSUE THREAD

**Issue by bleehu** [trowl223/Compound_X#9]
How does Prayer of silence react to walls? Can someone take cover against this?

**Comment by trowl223** [comment]
No, its not blockable except through counterspell.

**Comment by bleehu** [comment]
don't tell me; write it in the doc!

**Comment by trowl223** [comment]
I explicitly says "each character," so it isn't affected by cover.

**Comment by bleehu** [comment]
That's still not specific enough. Please mention cover specifically.

**Comment by trowl223** [comment]
Each character means each character. This isn't a direct attack or an explosion, it's a siphon effect.

**Comment by trowl223** [comment]
Added spell types to Paladin Spells. Paladin Spells also now state that by default no spells are affected by cover unless written into th description. I'll probably extend the same to Mage and Sorcerer spells. Paladin spells are mostly weapon augments and buffs to allys, so this default doesn't worry me. Most of the Mage and Sorcerer spells will have to have "Spell DC affected by target's cover" to relevant spells.
