### ISSUE TITLE
Traits: Reusable D-filter vs Quick Constriction

### ISSUE THREAD

**Issue by Turtlelord26** [trowl223/Compound_X#913]
These two traits are very similar. I would say too similar. Action item is to change one to be a more unique trait.

Personally, I like D-filter's flavor better, probably because of how it fits into that little meta-system Drones have gong on with the vision upgrade traits. However, good ideas trump preexisting preferences.

**Comment by bleehu** [comment]
Where's Quick constriction?

**Comment by Turtlelord26** [comment]
https://github.com/bleehu/Compound_X/blob/dev/CharacterCreation/01_01_Species_Human.txt#L165

**Comment by bleehu** [comment]
I'm not worried about one almost-duplicated species trait, the combination of traits will still be unique. If you'd really like to mandate that each be unique, I'll update D-filter.

**Comment by Turtlelord26** [comment]
As long as we keep the species distinct, I'm good. The easiest systematic way to do that from a design perspective is a blanket ban on clone or near-clone traits. However, I have decided I'm willing to ship these two traits to RC and see what happens.
