### ISSUE TITLE
New Melee Feat Proposal

### ISSUE THREAD

**Issue by Turtlelord26** [trowl223/Compound_X#926]
Melee characters want a feat that keeps specialists from disengaging, drawing a machine gun, aiming, and hosing them down.
Proposition is a feat that, if a character succeeds on an attack of opportunity with a melee weapon against an opponent trying to move out of a threatened square (success meaning deals damage to health), the enemy's movement full stops.
Should be some decently hefty prereqs on this.

**Comment by rosebrallier** [comment]
Sentinel, yes!

Rose Brallier
