### ISSUE TITLE
Dog level progression.

### ISSUE THREAD

**Issue by Wildlovelies** [trowl223/Compound_X#927]
Dogs level progression for hp and or skills not available

**Comment by bleehu** [comment]
No characters get hp progression.

Dog has only the perform and investigate skills, investigate scales per level: https://github.com/bleehu/Compound_X/commit/4728f34c73d58ab1829e27b870d53699943c075b#diff-36777511a6ead9e8ceca798c004035a8R34. 

Attack also scales per level: https://github.com/bleehu/Compound_X/commit/4728f34c73d58ab1829e27b870d53699943c075b#diff-36777511a6ead9e8ceca798c004035a8R42

If the soldier scales as characters do, but the hunter scales as characters do *AND* his dog scales at the same rate, then the hunter has two degrees of freedom scaling, while the soldier has only one. Thus the hunter will outrun the rest of the classes and become unbalanced. 

As it is, Assault rifles *should* be scaling quicker than shotguns to keep it in line with Doc/Engineer scaling with abilities, and the hunter's dog scales at a rate that is within tolerances. There is an ongoing project to better attempt to quantify character balance. Pending the results of that work, we won't know what balance looks like.
