### ISSUE TITLE
Gripe: Muscle Memory Wording

### ISSUE THREAD

**Issue by rosebrallier** [trowl223/Compound_X#938]
> Negate the pump of a shotgun, cocking of a revolver, or cycling of a bolt 
> when performing another action besides the aforementioned (besides firing).

What even is this
In [Muscle Memory](https://github.com/bleehu/Compound_X/blob/6117aea0b1452e5f6c587522910cd4ad2947718e/CharacterCreation/03_Feats.txt#L324) feat

**Comment by Turtlelord26** [comment]
I think (?) it's trying to say something like you can pump a shotgun during a move action (or going prone, etc.)

**Comment by bleehu** [comment]
Oh! That makes more sense! I wasn't playing this right!
