### ISSUE TITLE
Balance check on focal lensing weapon attachment

### ISSUE THREAD

**Issue by bleehu** [trowl223/Compound_X#944]
Seems expensive for little damage gain?

**Comment by Turtlelord26** [comment]
Link the line please?

**Comment by bleehu** [comment]
Whoops! My bad! https://github.com/bleehu/Compound_X/blob/play/Items/04_00_WeaponAttachments.txt#L316

**Comment by Turtlelord26** [comment]
I think it's a breakpoint argument. Combine with maxed out expertise (it's lv 10 after all) and were talking a lot of damage. Characters are squishy.

The attachment above for ballistic plasma is almost identical

**Comment by bleehu** [comment]
You've convinced me.
