### ISSUE TITLE
Certain feats dont explain what they do

### ISSUE THREAD

**Issue by Masterdiekillsu** [trowl223/Compound_X#95]
In particular, the feats:
The Stealth Option
Acquired: With Friends Like These . . .
Acquired: . . . Who Needs Nano-Technologies?

These feats do not have the explanation for what they do. They have the prerequisites, but that's it. 

This is in the Play, player rules, character creation, feats section.

**Comment by bleehu** [comment]
Good bug. Which Branch?

**Comment by Masterdiekillsu** [comment]
It is in the "play" branch
It's also possible that this error has carried over into other branches as well

**Comment by bleehu** [comment]
Taylor apparently says that they are surprise feats. You find out what they do when you take the feat.
