### ISSUE TITLE
Feature Request: More misc Items

### ISSUE THREAD

**Issue by bleehu** [trowl223/Compound_X#96]
We had a good start on miscellaneous items in the 07 items doc, but we could always use more! 

Canteens, Compasses, Flint n Steel, RC cars, maybe some musical instruments and salvage tools have all cropped up in gameplay. I think they are likley to pop up again, but we still don't have any idea what they should cost or what their stats (if any) should be.

Feeling creative?

**Comment by Masterdiekillsu** [comment]
@bleehu if we make some items, how would you like us to handle and store them? Like where should we make our lists, and how would you like us to upload them?

**Comment by bleehu** [comment]
Make a pull request to the dev branch with an updated items file. Turtle can help



Sent from my Verizon, Samsung Galaxy smartphone


-------- Original message --------
